### ISSUE TITLE
Import Module: stiximport fails to import 'category="ipv4-addr"'

### ISSUE THREAD

**Issue by davidonzo** [MISP/misp-modules#104]
I'm working on my test MISP environment.
The misp-module stiximport seems to ignore IPV4 indicators (not yet tested with IPV6).

I'm testing the import using Grizzly Steppe STIX xml indicators, released by US-CERT: https://www.us-cert.gov/security-publications/GRIZZLY-STEPPE-Russian-Malicious-Cyber-Activity.
The import give no error, but in the results form available there's not IPv4 indicators listed.

Any solution? Thanks in advance for your support.

**Comment by Rafiot** [comment]
Fixed by https://github.com/MISP/MISP-STIX-Converter/commit/1b0d879b07643bbac8fe5de9285e347c029ef860 :)

As last time, just update the misp stix library: 

`pip install -U git+https://github.com/MISP/MISP-STIX-Converter.git#egg=misp_stix_converter`

**Comment by davidonzo** [comment]
Thank you very much again!
All works fine after the update! :+1: 

Have a nice weekend!
