### ISSUE TITLE
Fresh install fails to start

### ISSUE THREAD

**Issue by xme** [MISP/misp-modules#113]
# sudo -u www-data misp-modules -s
Traceback (most recent call last):
  File "/usr/local/bin/misp-modules", line 9, in <module>
    load_entry_point('misp-modules==1.0', 'console_scripts', 'misp-modules')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2568, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'misp-modules') not found

Any idea?

**Comment by dawid-czarnecki** [comment]
Uninstall first and then install again
```
pip3 uninstall misp-modules
git pull
git diff
pip3 install -I .
```
or if you install directly from pip packages
`pip3 install -I misp-modules`

**Comment by adulau** [comment]
I think this is a very old issue and not applicable any more.  

The official standard way is the one mentioned in the README:

https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules

Let me know if this is working. I'll close the issue and feel free to reopen if the issue persists.

**Comment by dawid-czarnecki** [comment]
I had it yesterday and this is how I solved it with @cvandeplas.

**Comment by adulau** [comment]
@dawid-czarnecki if you do just the (re)install  from README, it doesn't work?
