### ISSUE TITLE
Seg Fault while Installing misp-modules

### ISSUE THREAD

**Issue by maddog317** [MISP/misp-modules#116]
pip3 install -I .

Processing /usr/local/src/misp-modules
Collecting tornado (from misp-modules===1.0)
Collecting dnspython3 (from misp-modules===1.0)
Collecting requests (from misp-modules===1.0)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting urlarchiver (from misp-modules===1.0)
Collecting passivetotal (from misp-modules===1.0)
Collecting PyPDNS (from misp-modules===1.0)
Collecting pypssl (from misp-modules===1.0)
Collecting redis (from misp-modules===1.0)
  Using cached redis-2.10.5-py2.py3-none-any.whl
Collecting pyeupi (from misp-modules===1.0)
Collecting ipasn-redis (from misp-modules===1.0)
Collecting asnhistory (from misp-modules===1.0)
Collecting stix (from misp-modules===1.0)
  Using cached stix-1.2.0.3-py2.py3-none-any.whl
Collecting cybox (from misp-modules===1.0)
Collecting pillow (from misp-modules===1.0)
  Using cached Pillow-4.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pytesseract (from misp-modules===1.0)
Collecting shodan (from misp-modules===1.0)
Collecting dnspython==1.15.0 (from dnspython3->misp-modules===1.0)
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting url-normalize (from urlarchiver->misp-modules===1.0)
  Using cached url_normalize-1.3.1-py3-none-any.whl
Collecting future (from passivetotal->misp-modules===1.0)
Collecting python-dateutil (from passivetotal->misp-modules===1.0)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting ez-setup (from passivetotal->misp-modules===1.0)
Collecting requests-cache (from PyPDNS->misp-modules===1.0)
  Using cached requests_cache-0.4.13-py2.py3-none-any.whl
Collecting dateutils (from asnhistory->misp-modules===1.0)
Collecting mixbox>=1.0.1 (from stix->misp-modules===1.0)
  Using cached mixbox-1.0.1-py2.py3-none-any.whl
Collecting lxml>=2.3 (from stix->misp-modules===1.0)
  Using cached lxml-3.7.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting olefile (from pillow->misp-modules===1.0)
Collecting colorama (from shodan->misp-modules===1.0)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting simplejson (from shodan->misp-modules===1.0)
Collecting click (from shodan->misp-modules===1.0)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting click-plugins (from shodan->misp-modules===1.0)
Collecting six>=1.5 (from python-dateutil->passivetotal->misp-modules===1.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting argparse (from dateutils->asnhistory->misp-modules===1.0)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting pytz (from dateutils->asnhistory->misp-modules===1.0)
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting ordered-set (from mixbox>=1.0.1->stix->misp-modules===1.0)
Building wheels for collected packages: misp-modules
  Running setup.py bdist_wheel for misp-modules ... done

Successfully built misp-modules

Installing collected packages: tornado, dnspython, dnspython3, requests, url-normalize, urlarchiver, future, six, python-dateutil, ez-setup, passivetotal, requests-cache, PyPDNS, pypssl, redis, pyeupi, ipasn-redis, argparse, pytz, dateutils, asnhistory, ordered-set, lxml, mixbox, cybox, stix, olefile, pillow, pytesseract, colorama, simplejson, click, click-plugins, shodan, misp-modules
Successfully installed PyPDNS-1.3 argparse-1.4.0 asnhistory-2.0.4 click-6.7 click-plugins-1.0.3 colorama-0.3.7 cybox-2.1.0.13 dateutils-0.6.6 dnspython-1.15.0 dnspython3-1.15.0 ez-setup-0.9 future-0.16.0 ipasn-redis-2.0 lxml-3.7.3 misp-modules-1.0 mixbox-1.0.1 olefile-0.44 ordered-set-2.0.1 passivetotal-1.0.30 pillow-4.0.0 pyeupi-1.0 pypssl-2.1 pytesseract-0.1.6 python-dateutil-2.6.0 pytz-2016.10 redis-2.10.5 requests-2.13.0 requests-cache-0.4.13 shodan-1.6.4 simplejson-3.10.0 six-1.10.0 stix-1.2.0.3 tornado-4.4.2 url-normalize-1.3.1 urlarchiver-0.2

You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Segmentation fault (core dumped)

**Comment by Rafiot** [comment]
This is... interesting. Can you try to run pip install --upgrade pip? Just in case...
