### ISSUE TITLE
Email Import Module Errors out when it encounters unrecognized chars in subject

### ISSUE THREAD

**Issue by cyber-guy** [MISP/misp-modules#119]
When emails contain characters that the native encoding cannot map to, the module will return a generic error “Something went wrong, look in the server logs for details”
 
This appears due particularly to email subjects like"🚀<non ascii char> john smith ? You are welcome" and there are two errors I found:
 
**1.      all_headers += "{0}: {1}\n".format(k.strip(), v.strip())
AttributeError: 'Header' object has no attribute 'strip'**
 
A string cannot be returned because the unrecognized character cannot be encoded, so a ‘Header object’ gets returned, but as Header objects are not strings, the .strip() method will not work.
 
Possible solution is to apply the strip method in the results appending and also always encode the all_headers value so a string is returned regardless of unrecognized characters:
                       all_headers += "{0}: {1}\n".format(k, v)
   results.append({"values": all_headers.strip().encode('utf-8'), "type": 'email-header'})
 
**2.      results.append({"values": message.get('Subject'), "type": 'email-subject'})  grabs the subject, but it would get returned as an ‘Header object’ and not the actual subject.**
 
Example: 'type': 'email-subject', 'values': <email.header.Header object at 0x02BED890>
 
Possible solution is the same as item one, always encoding the subject.
results.append({"values": message.get('Subject').encode('utf-8'), "type": 'email-subject'})

**Comment by seamustuohy** [comment]
Hey @cyber-guy can you provide an e-mail example that I can test against while I troubleshoot it?

**Comment by cyber-guy** [comment]
[unrecognized_chars.txt](https://github.com/MISP/misp-modules/files/1117437/unrecognized_chars.txt)

Sorry for the delay. Here's one that had issues due to unrecognized characters. Below is the code i ended up going up with (Note: there may also be issues if the attachment name is encoded but i haven't looked into that much yet)

	# Extract all header information
	all_headers = ""
	try:
		for k,v in message.items():
			all_headers += "{0}: {1}\n".format(k.strip(), v.strip())
	# FIX: Account for times when header components are encoded, i.e. Subject
	except:
		from email.parser import HeaderParser	
		headers = HeaderParser().parsestr(str(message))
		for k,v in headers.items():
			all_headers += "{0}: {1}\n".format(k.strip(), v.strip())
	results.append({"values": all_headers, "type": 'email-header'})

	# Subject
	if message.get('Subject'):
		#results.append({"values": message.get('Subject'), "type": 'email-subject'})	
		# FIX: Account for times the Subject is encoded or contains special chars
		from email.header import decode_header
		subject, encoding = decode_header(message.get('Subject'))[0]
		if encoding != None:
			try:
				subject = subject.decode(encoding)
			except:
				subject = subject.decode('cp437')		
		results.append({"values": subject, "type": 'email-subject'})

**Comment by seamustuohy** [comment]
Working on the tests to reproduce this now and I wanted to say **thank you** for reporting it and providing an example. This is very closely related to issue #93 which I could not reproduce. It turns out that my unit tests were using e-mails that were following the spec to closely, and therefore, not able to reproduce the issue. Your example allowed me to figure out how to reproduce the issue for both of these.

**Comment by Rafiot** [comment]
Fixed
