### ISSUE TITLE
Can't import US-CERT STIX files

### ISSUE THREAD

**Issue by RichieB2B** [MISP/misp-modules#143]
When importing the STIX document from https://www.us-cert.gov/ncas/alerts/TA17-318B into MISP using the Stiximport module the following error is thrown:
```
misp_stix_converter.errors.STIXLoadError: Could not load stix file. Namespace not found: http://us-cert.gov/ciscp
```

**Comment by RichieB2B** [comment]
I was able to load this file using this code:
```
#!/usr/bin/env python

from stix.core import STIXPackage
from mixbox.namespaces import Namespace

NAMESPACES = [
    Namespace('http://us-cert.gov/ciscp', 'CISCP', 'http://www.us-cert.gov/sites/default/files/STIX_Namespace/ciscp_vocab_v1.1.1.xsd')
]

def _update_namespaces():
    # Update the python-stix namespace dictionary
    from stix.utils import nsparser
    import mixbox.namespaces

    nsparser.STIX_NAMESPACES.add_namespace(NAMESPACES[0])
    mixbox.namespaces.register_namespace(NAMESPACES[0])

_update_namespaces()
fn = 'TA VOLGMER IOCs.xml'
stix_package = STIXPackage.from_xml(fn)
```

Should the stix importer dynamically register the namespaces from the STIX header?

**Comment by FloatingGhost** [comment]
Fixed as of MISP-STIX-Converter/8bb6f288a

**Comment by RichieB2B** [comment]
OMG, dynamic namespace loading! You are a true STIX god! Thank you.

**Comment by RichieB2B** [comment]
Link to the excellent https://github.com/MISP/MISP-STIX-Converter/commit/8bb6f288aacc457443921d7b3da4924f46da99f8 patch for reference sake. Thanks again!

**Comment by adulau** [comment]
I suppose we can close this one based on the recent STIX 1.1 import in MISP core.
