### ISSUE TITLE
Virustotal enrichment always suggests MD5

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-modules#162]
Using MISP 2.4.87 and a fresh _git pull_ it seems that the VT module always suggests MD5 as the file enrichment type whereas it should be quite simple to recognize from the value the correct hash algorithm. Or is this expected behaviour:

![vt](https://user-images.githubusercontent.com/25325656/36424161-a91d516e-1642-11e8-8498-e3d62d1c01fe.png)

(or should this reported over at MISP core?)

**Comment by iglocska** [comment]
At first glance, very uneducated glance it looks like it's this:

https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/virustotal.py#L155

Just pushed a blind fix, could you try it?

https://github.com/MISP/misp-modules/commit/978903f9111bd62bbc63d5150e89969bbb1b1856

**Comment by StefanKelm** [comment]
Not quite...

Now the "Category" presents an empty pull-down menu, and the "Type" says _hashes_...
