### ISSUE TITLE
Taxonomies Internal Error Has Occurred

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/misp-modules#175]
Fresh install of MISP, just now getting around to them.  
I have one for Feeds and one is a Master.  Both are showing same issue when updating the taxonomies for the first time.  Not sure if it means my DB is busted or it's something else.  Found this in the error log from:  /var/www/MISP/app/tmp/logs

2018-03-24 12:28:25 Error: [PDOException] SQLSTATE[42S22]: Column not found: 105                                                                                                                                                             4 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /taxonomies
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): P                                                                                                                                                             DOStatement->execute(Array)

#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): D                                                                                                                                                             boSource->_execute('SELECT COUNT(*)...', Array)

#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): D                                                                                                                                                             boSource->execute('SELECT COUNT(*)...', Array, Array)

#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184):                                                                                                                                                              DboSource->fetchAll('SELECT COUNT(*)...', Array)

#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read                                                                                                                                                             (Object(Tag), Array)

#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDat                                                                                                                                                             aSource('count', Array)

#6 /var/www/MISP/app/Controller/TaxonomiesController.php(31): Model->find('count                                                                                                                                                             ', Array)

#7 [internal function]: TaxonomiesController->index()

#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): Reflec                                                                                                                                                             tionMethod->invokeArgs(Object(TaxonomiesController), Array)

#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controlle                                                                                                                                                             r->invokeAction(Object(CakeRequest))

#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatch                                                                                                                                                             er->_invoke(Object(TaxonomiesController), Object(CakeRequest))

#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeReq                                                                                                                                                             uest), Object(CakeResponse))

#12 {main}

This from debug:

2018-03-24 11:55:12 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Controller/UsersController.php, line 1172]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::__extralog() - APP/Controller/UsersController.php, line 1172
UsersController::change_pw() - APP/Controller/UsersController.php, line 185
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

All the workers appear to be healthy as well, and the rest of the app appears to be healthy as well...

Jimbo

**Comment by jimbolya0607** [comment]
Also - really quick:  the tables appear to be in the db for taxonomies and tags...

+-------------------------------+
| Tables_in_mastermisp          |
+-------------------------------+
| admin_settings                |
| attribute_tags                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_blacklists              |
| event_delegations             |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| galaxies                      |
| galaxy_clusters               |
| galaxy_elements               |
| galaxy_reference              |
| jobs                          |
| logs                          |
| news                          |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| org_blacklists                |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightings                     |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| whitelist                     |
+-------------------------------+
54 rows in set (0.00 sec)

**Comment by adulau** [comment]
Strange. Which version are you using? "'Tag.user_id'" issue was present in an old version.

**Comment by jimbolya0607** [comment]
2.4.87

**Comment by jimbolya0607** [comment]
i'll feel like a total ass if all i had to do was update it lol.

**Comment by jimbolya0607** [comment]
Bang!
Working now...i'm such a dolt sometimes...err most of the time. 
Thanks sir!!

**Comment by adulau** [comment]
Great that it works.
