### ISSUE TITLE
IBM X-Force Install

### ISSUE THREAD

**Issue by Glhenn** [MISP/misp-modules#204]
I get the feeling that i missing something. I trying to connect my X-force acc with misp, but i cannot even get the module/expansion to appear. How do i even config it. Portal?

**Comment by adulau** [comment]
If have the modules enabled on your MISP, you have to go in "Server Settings & Maintenance" then Plugin settings and then you can select xforce plugin enable and put your API key:

![xforce](https://user-images.githubusercontent.com/3309/42323212-a2cf9948-805f-11e8-9dea-71b7cceffc94.png)

I hope this helps.

**Comment by Glhenn** [comment]
Ah. Thanks. I didn’t install the modules correctly. All fixed. Thanks mate

**Comment by adulau** [comment]
@Glhenn Thanks for the feedback. Enjoy MISP ;-)
