### ISSUE TITLE
IBM X-Force Import Module (more than manual on-demand enrichment)

### ISSUE THREAD

**Issue by github-germ** [MISP/misp-modules#205]
I am aware of an IBM X-Force plugin that does WebUI user activated on-demand attribute enrichment .

Is anyone aware of an import module for IBM X-Force that will actually ingest events with those attributes into MISP?

**Comment by adulau** [comment]
We accept pull-request for an updated MISP - IBM X-Force module. I don't have access to X-Force... feel free to share API keys with us ;-)
