### ISSUE TITLE
Spamhaus DBL lookup module (enrichment)

### ISSUE THREAD

**Issue by abusech** [MISP/misp-modules#212]
It would be nice to have a module that checks Spamhaus DBL for a domain name.

Based on the DNSBL return codes, the module could say whether the domain name is spam, phishing, malware or botnet and/or whether it is compromised or not:

https://www.spamhaus.org/faq/section/Spamhaus%20DBL#291

**Comment by adulau** [comment]
~~~~
127.0.1.2 | spam domain
-- | --
127.0.1.4 | phish domain
127.0.1.5 | malware domain
127.0.1.6 | botnet C&C domain
127.0.1.102 | abused legit spam
127.0.1.103 | abused spammed redirector domain
127.0.1.104 | abused legit phish
127.0.1.105 | abused legit malware
127.0.1.106 | abused legit botnet C&C
127.0.1.255 | IP queries prohibited!
~~~~

**Comment by adulau** [comment]
Thanks to @chrisr3d  he did a new module during the hackathon. https://github.com/MISP/misp-modules/pull/214 Feel free to test and review.

**Comment by chrisr3d** [comment]
If you want an overview, here is the result it should provide:
![screenshot from 2018-08-08 16-41-58](https://user-images.githubusercontent.com/16307976/43847676-734f694a-9b31-11e8-80ac-95e4516b93a7.png)
