### ISSUE TITLE
Make Redis location configurable

### ISSUE THREAD

**Issue by ilyaglow** [MISP/misp-modules#224]
Hey there,

Redis cache location is now [hardcoded to be localhost only](https://github.com/MISP/misp-modules/blob/master/misp_modules/helpers/cache.py#L25-L27). I think it would be great if a user could define redis location using environment variable or `misp-modules` command line key.

What you think?

The first approach is very easy to implement and I can [send a PR](https://github.com/ilyaglow/misp-modules/commit/1f9198f09147ce15433ceb9d3e700c55fe2b9136) if you wish.

**Comment by 8ear** [comment]
+1

**Comment by ilyaglow** [comment]
Looks like it was fixed a while ago: https://github.com/MISP/misp-modules/pull/259 @8ear .
No handling for `REDIS_USER` and `REDIS_PASSWORD` though.
I suggest you to open a new issue for this feature.
