### ISSUE TITLE
Ubuntu 16.04.5 domaintools_api issue

### ISSUE THREAD

**Issue by SteveClement** [MISP/misp-modules#244]
The [domaintools_api](https://github.com/DomainTools/python_api/) has a minimum aiohttp requirement of 3.4.4 whilst aiohttp 3.x needs Python 3.5.3 minimum.

Ubuntu 16.04-LTS only has 3.5.2 that is easily installed.

domaintools_api issue: https://github.com/DomainTools/python_api/issues/31

Previously erroneously opened here: https://github.com/MISP/PyMISP/issues/292

**Comment by SteveClement** [comment]
A workaround is to update Python3.5 to Python3.6

```bash
$ sudo add-apt-repository ppa:jonathonf/python-3.6
$ sudo apt-get update
$ sudo apt-get install python3.6
```

**Comment by Rafiot** [comment]
\o/

Practical question: when do we move the default recommended ubuntu version to 18.04?

**Comment by SteveClement** [comment]
> \o/
> 
> Practical question: when do we move the default recommended ubuntu version to 18.04?

April 2021 like @iglocska and @adulau would now say :smiley_cat:

**Comment by SteveClement** [comment]
My spidey senses tell me this will be a no-fix...
