### ISSUE TITLE
[PATCH] ONYPHE patch to cope with changes in results returned from the API for pastries and resolver

### ISSUE THREAD

**Issue by onyphe** [MISP/misp-modules#252]
Please find a patch that fixes the issue of not having any results from a search for an IP address in pastries and resolver data. As we have changed the way we handle different types of documents, this patch is mandatory to be able to have results from this MISP module.
[onyphe-patch.txt](https://github.com/MISP/misp-modules/files/2569413/onyphe-patch.txt)

**Comment by adulau** [comment]
Thank you. Could you a do pull-request?

**Comment by onyphe** [comment]
Unfortunately not. Being forced to fork a project, patch it, do the pull request and then clean up the forked project appears a little bit too heavy for us. We prefer the old school way of sending patches in diff format.

Best regards,


--
https://www.onyphe.io
One if is enough
Twitter: @onyphe

On 11/11/2018 15:18, Alexandre Dulaunoy wrote:

Thank you. Could you a do pull-request?

**Comment by adulau** [comment]
I applied the patch. Thank you for the contribution.

**Comment by onyphe** [comment]
You're welcome. We are happy that MISP is plugged with ONYPHE :)


--
https://www.onyphe.io
One if is enough
Twitter: @onyphe

On 11/11/2018 15:52, Alexandre Dulaunoy wrote:

I applied the patch. Thank you for the contribution.
