### ISSUE TITLE
destination path 'misp-modules' already exists and is not an empty directory

### ISSUE THREAD

**Issue by htwhere** [MISP/misp-modules#262]
misp@misp:/usr/local/src$ sudo git clone https://github.com/MISP/misp-modules.git
fatal: destination path 'misp-modules' already exists and is not an empty directory.
misp@misp:/usr/local/src$

**Comment by adulau** [comment]
The directory is already cloned (as mentioned in the output message).  If you want to update the existing local repository:

~~~~
cd /usr/local/src/misp-modules
git pull origin master
~~~~

FYI, there is a very good introduction to git on GitHub [Git Handbook](https://guides.github.com/introduction/git-handbook/)

I hope this helps.

**Comment by pcazador2021** [comment]
Hola, intenté compilar este archivo y obtuve este error: git clone https://github.com/fventuri/codecserver-mbelib-module.git
Fatal: La ruta de destino 'codecserver-mbelib-module' ya existe y no es un directorio vacío.
