### ISSUE TITLE
how to use MISP REST CLIENT?

### ISSUE THREAD

**Issue by htwhere** [MISP/misp-modules#263]
Hi how to use MISP REST CLIENT?  i want to query Alentvault OTX or Virus Total  or  IBM X-Force exchange and PaloAlto AutoFOUCS

**Comment by SteveClement** [comment]
There is sparse information here:

https://www.misp-project.org/misp-training/a.7-rest-API.pdf
https://misp.gitbooks.io/misp-book/content/automation/#post-events

But best would be you join this channel: https://gitter.im/MISP/Support

Also, make sure to discover the new Query builder, which does a good job at leading you towards what you want to achieve.
