### ISSUE TITLE
Cloning https://github.com/MISP/PyIntel471.git to /tmp/pip-bgfzozdk-build  connection broken

### ISSUE THREAD

**Issue by htwhere** [MISP/misp-modules#265]
misp@misp:/usr/local/src/misp-modules$ sudo pip3 install -I -r REQUIREMENTS
The directory '/home/misp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/misp/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/MISP/PyIntel471.git (from -r REQUIREMENTS (line 31))
  Cloning https://github.com/MISP/PyIntel471.git to /tmp/pip-bgfzozdk-build
Collecting tornado (from -r REQUIREMENTS (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb770e940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/tornado/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb770ecc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/tornado/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb770e080>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/tornado/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb770e320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/tornado/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb770eeb8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/tornado/
  Could not find a version that satisfies the requirement tornado (from -r REQUIREMENTS (line 1)) (from versions: )
No matching distribution found for tornado (from -r REQUIREMENTS (line 1))

**Comment by Rafiot** [comment]
Same as: https://github.com/MISP/misp-modules/issues/264, connectivity issue.
