### ISSUE TITLE
Easing deployment: implement as installable application

### ISSUE THREAD

**Issue by dspruell** [MISP/misp-modules#27]
Will the project be open to implementing MISP modules as an installable Python package and publishing releases on PyPI? It would be fantastic to simply `pip install misp-modules` or similar, and for the script at *bin/misp-modules.py* to be migrated to a setuptools entry-point.

This would significantly ease deployment and aid use cases like installing into a virtualenv, etc.

**Comment by Rafiot** [comment]
Good point, I'll try to do that :)

**Comment by Rafiot** [comment]
(note that it isn't a pip package right now, I'll upload it on pip in the next days, but if you already want to try the installer, that would be cool)
