### ISSUE TITLE
unable to load, no module pybgpranking

### ISSUE THREAD

**Issue by cowbe0x004** [MISP/misp-modules#270]
I'm following this guide https://misp.github.io/MISP/INSTALL.debian9/ and pretty much stuck on starting misp-modules. I did everything exactly the same except getting permission error when installing the modules in virtualenv, so I did it with pip3 instead.

As can be seen here, pybgpranking is installed. Did I install it in a wrong place? I can start misp-module without any argument. 

root@misp-prox:/var/www/MISP/venv/bin# sudo -u www-data ${PATH_TO_MISP}/venv/bin/misp-modules -l 0.0.0.0 -s &
[1] 6111
root@misp-prox:/var/www/MISP/venv/bin# No module named 'pybgpranking'
2019-01-25 22:52:00,412 - misp-modules - INFO - Launch MISP modules server from package.
2019-01-25 22:52:00,413 - misp-modules - INFO - Helper loaded cache
2019-01-25 22:52:00,414 - misp-modules - INFO - Unable to load MISP modules from package.

[1]+  Done                    sudo -u www-data ${PATH_TO_MISP}/venv/bin/misp-modules -l 0.0.0.0 -s

root@misp-prox:/var/www/MISP/venv/bin# pip3 install pybgpranking
Requirement already satisfied: pybgpranking in /usr/local/src/misp-modules/src/pybgpranking/client
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from pybgpranking)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->pybgpranking)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->pybgpranking)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->pybgpranking)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->pybgpranking)

root@misp-prox:/var/www/MISP/venv/bin# pip3 freeze |grep pybgpranking
-e git+https://github.com/D4-project/BGP-Ranking.git/@7e698f87366e6f99b4d0d11852737db28e3ddc62#egg=pybgpranking&subdirectory=client

root@misp-prox:/var/www/MISP/venv/bin# misp-modules -s
invalid syntax (api.py, line 82)
2019-01-25 23:01:54,034 - misp-modules - INFO - Launch MISP modules server from package.
2019-01-25 23:01:54,035 - misp-modules - INFO - Helper loaded cache
2019-01-25 23:01:54,036 - misp-modules - INFO - Unable to load MISP modules from package.

**Comment by Rafiot** [comment]
So I think there are two issues:
* `invalid syntax (api.py, line 82)` is from pyipasnhistory, because it requires at least python 3.6.
* pybgpranking should not require python 3.6, but you don't have the error when you run the modules as root, so I guess it isn't installed in the virtualenv.

**Comment by cowbe0x004** [comment]
but pip freeze shows it's installed....

I guess I'll try to follow the steps again as non-root user. Thank you.

**Comment by Rafiot** [comment]
Yes, it is installed when you run this command: `root@misp-prox:/var/www/MISP/venv/bin# misp-modules -s`

**Comment by cowbe0x004** [comment]
Thank you. The install guides for both ubuntu and debian are wrong to "chown root:staff /usr/local/src". Instead I chown www-data:www-data.

**Comment by Rafiot** [comment]
Hmm, ok, I have no idea about that, it seems "staff" has been changed a few month ago, I'm not sure why (cc @SteveClement).

I was talking about the purely python-related issues you have.

**Comment by 9b** [comment]
I too am having this issue. 

```
misp@ubuntu:/var/www/MISP/venv/bin$ sudo -H -u www-data ${PATH_TO_MISP}/venv/bin/pip3 install pybgpranking
Collecting pybgpranking
  Could not find a version that satisfies the requirement pybgpranking (from versions: )
No matching distribution found for pybgpranking
```

**Comment by Rafiot** [comment]
pybgpranking isn't on pypi so you have to install it using the repository. 

Either like that: 
`sudo -H -u www-data ${PATH_TO_MISP}/venv/bin/pip3 install git+https://github.com/D4-project/BGP-Ranking.git/@7e698f87366e6f99b4d0d11852737db28e3ddc62#egg=pybgpranking&subdirectory=client`

or by installing all the dependencies listed in the REQUIREMENTS file (as explained [in the documentation](https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules))

**Comment by 9b** [comment]
All good, thank you!

**Comment by Rafiot** [comment]
:+1:
