### ISSUE TITLE
Tag or release

### ISSUE THREAD

**Issue by kalyparker** [MISP/misp-modules#296]
Hello,

The last update missed requirement, what @Rafiot had identify.
With the official documentation  https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.ubuntu1804.md
I use these package for avoiding error:
sudo apt-get install python3-dev python3-pip libpq5 libjpeg-dev tesseract-ocr libpoppler-cpp-dev imagemagick virtualenv libopencv-dev zbar-tools libfuzzy-dev -y
instead of sudo apt-get install libpq5 libjpeg-dev libfuzzy-dev -y

Anyway, It is possible to add **tag** or **release** version on this project for adding "stability" on this project ?

I'll try to update the INSTALL on misp repo this week end.

Thanks

**Comment by adulau** [comment]
Indeed, this is a good point. The [generic documentation for MISP modules](https://github.com/MISP/MISP/commit/00f9c27667592bad77155cec77b6a68530ccc09a) and also the README for misp-modules has been updated.

The best source (in case we forgot to update a documentation somewhere) for the installation is the [Travis build script](https://github.com/MISP/misp-modules/blob/master/.travis.yml#L14)  and the [Pipfile](https://github.com/MISP/misp-modules/blob/master/Pipfile). 

Starting from Today, we will also tag misp-modules with the corresponding version of MISP core.

The [MISP release check list has been updated](https://github.com/MISP/MISP/wiki/ReleaseCheckList).

Thanks a lot for your feedback!
