### ISSUE TITLE
Installation and management instructions for extensions

### ISSUE THREAD

**Issue by 9b** [MISP/misp-modules#3]
Is there a published set of documents I can reference to test my extension? It's not entirely clear where they should be installed and how I can manage them within my MISP instance.

**Comment by adulau** [comment]
Sure. I'll publish tonight a set of slides used in the MISP training with example how to test your misp-modules.

**Comment by 9b** [comment]
Thanks @adulau!

**Comment by adulau** [comment]
Hi @9b,

As promised, the slides about the MISP modules are available:

https://www.circl.lu/assets/files/misp-training/3.1-MISP-modules.pdf

If you have any question, feel free.

Cheers

**Comment by passivetotal** [comment]
Thank you very much. This can now be closed!
