### ISSUE TITLE
Return values of modules as three-tuple

### ISSUE THREAD

**Issue by 3c7** [MISP/misp-modules#30]
Hi,

is it possible to implement the return values of modules as three-tuple?
E.g.: `(VALUE, CATEGORY, ATTRIBUTE_TYPE)`
The actual implementation needs the user to assign categories and types which takes, when importing lots of information, time. From my point of view, it is easier for users, when the assigning-step is optional and the module pre-assigns all the stuff. The user just checks if the assignments are correct, at the end.

Kind regards
Nils

**Comment by MichaelDwucet** [comment]
To elaborate on that matter. 
We have the use case that we are developing a misp module that will enhance an MISP event with results from an internal analysis system. 
As an example: We take an MD5 from MISP and the module will enrich the event with known other Hash-sums of the file (SHA1, SSDEEP), AV Detection names, an internal rating, ...

So the module will deliver results of the following types
Category: Internal Reference, Type: Comment
Category: Payload Delivery: Type: SHA1, SHA256, ...
Category: Antivirus detection, Type: Comment
and some more....

No we have two problems with the current implementation.
The first seems to be a bug.
You can define a list ($type, $value) (e.g. comment : value1, md5 : value2) but it seems that the results page ignores the type setting and set the type for every value to the type that is set for the first element.

The second problem is that just the type is not enough. We have results that are from the type comment, but are from different categories. So we would like to tell MISP the tupel (VALUE, CATEGORY, ATTRIBUTE_TYPE).

**Comment by iglocska** [comment]
Interesting. Looking into a solution for you guys, makes sense.

**Comment by iglocska** [comment]
Just a heads-up this is now implemented, just make sure you git pull on your MISP.

**Comment by adulau** [comment]
This should be fixed in MISP https://github.com/MISP/MISP/commit/53e2033568e1a5c3640c4a39e3ff6ef5e6f7536c - 

README of misp-modules has been updated "It is also possible to restrict the category options of the resolved attributes by passing a list of categories along (optional)" 

Let us know if you have any issues.

**Comment by 3c7** [comment]
Thank you very much, guys!
