### ISSUE TITLE
Infoblox Module

### ISSUE THREAD

**Issue by dmolina213** [MISP/misp-modules#313]
| Questions                 | Answers
|---------------------------|--------------------
Type of issue | support
OS version (server) | RedHat - Docker/ubuntu
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

I have MISP running on Docker /Ubuntu. The server itself is RHEL7. I need assistance creating an expansion module for Infoblox. Infoblox  provided me with a username and an API key. Based on going thru the configuration guides out there I am supposed to:

1. Created a file named Infloblox.py and place it in  /usr/local/src/misp-modules/misp_modules/modules/expansion
- what code should i include in here? Can I simply copy and paste mosst content from circl_passivedns.py  and only make specific changes based on specifics of infoblox? Since inflobox mostly provides passivedns info, whois information. The information provided is almost similar. It is just that we have a premium service enabled in infoblox.

2. I know i have to add the infoblox information in __init.py__
3. What do i do next? How do I get MISP to read the infoblox module into the enrichment section of the plugin tab?

**Comment by adulau** [comment]
You need to create a new module, in order to do that, you can have a look at the training slides:

- [Extending MISP with Python modules](https://www.misp-project.org/misp-training/3.1-misp-modules.pdf).
- Carefully read the documentation of [InfoBlox API](https://www.infoblox.com/wp-content/uploads/infoblox-deployment-infoblox-rest-api.pdf) and look at what you need from this API.
- Then you can have a look at existing module like the CVE module which is doing HTTP request to a third-party services as example using the Python requests library.
 
I hope this helps.

**Comment by dmolina213** [comment]
my main goal for now is to be able to get my module to show up in the enrichments tab of the web interface. Once I am successful in that I can work with Infoblox to get the module to work the way we want it to. I am not a developer by trade, but I can read and understand code. I just cant start one from scratch. But I can barrow code from other modules for example, the CVE module you mentioned below. As far a placement of the files. Is this the correct directory /usr/local/src/misp-modules/misp_modules/modules/expansion  ?

So after creating the .py files and defining it in __init__py file. What is next? Will MISP automatically recognize the new modules and show them in the web UI or do we have to kick off some sort of process. I believe I read somewhere that it MISP would recognize it. But somehow another document was asking me to run some code:

• Python 3 is required to run MISP modules.
◦ sudo apt-get install python3-dev python3-pip libpq5 ◦
cd /usr/local/src/
◦ sudo git clone https://github.com/MISP/misp-modules.git
◦ cd misp-modules ◦ sudo pip3 install –upgrade -r REQUIREMENTS
◦ sudo pip3 install –upgrade .
◦ sudo vi /etc/rc.local, add this line: ‘sudo -u www-data misp-modules -s &‘

Will the instructions run on MISP running on docker on a VM that has RHEL. However, the MISP instance on docker is running over Ubuntu?

V/r

Douglas P Molina, MBA, CISSP, C|EH, CySA+
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 224-434-1203
UNCLASS: douglas.molina@va.gov<mailto:douglas.molina@va.gov>
[cid:image002.jpg@01D52CAB.16E2F4E0]

**Comment by dmolina213** [comment]
Also I have seen 2 versions of __init__.py. Which do I use? The 1st one works otherwise, how could have MISP enabled the other modules. Even though I am using the 1st one I still don’t see my module in the web UI. Also, I appreciate the slide deck, but if feel some of the important parts must have been delivered verbally, yes?


  1.  This one from github https://github.com/MISP/misp-modules/blob/master/misp_modules/__init__.py


  1.  And this one from /usr/local/src/misp-modules/misp_modules/modules/expansion



from . import _vmray  # noqa
import os
import sys
sys.path.append('{}/lib'.format('/'.join((os.path.realpath(__file__)).split('/')[:-3])))

__all__ = ['cuckoo_submit', 'vmray_submit', 'bgpranking', 'circl_passivedns', 'circl_passivessl',
           'countrycode', 'cve', 'dns', 'btc_steroids', 'domaintools', 'eupi',
           'farsight_passivedns', 'ipasn', 'passivetotal', 'sourcecache', 'virustotal',
           'whois', 'shodan', 'reversedns', 'geoip_country', 'wiki', 'iprep',
           'threatminer', 'otx', 'threatcrowd', 'vulndb', 'crowdstrike_falcon',
           'yara_syntax_validator', 'hashdd', 'onyphe', 'onyphe_full', 'rbl',
           'xforceexchange', 'sigma_syntax_validator', 'stix2_pattern_syntax_validator',
           'sigma_queries', 'dbl_spamhaus', 'vulners', 'yara_query', 'macaddress_io',
           'intel471', 'backscatter_io', 'btc_scam_check', 'hibp', 'greynoise', 'macvendors',
           'qrcode', 'ocr-enrich', 'pdf-enrich', 'docx-enrich', 'xlsx-enrich', 'pptx-enrich',
           'ods-enrich', 'odt-enrich', 'joesandbox_submit', 'joesandbox_query', 'urlhaus']
V/r

Douglas P Molina, MBA, CISSP, C|EH, CySA+
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 224-434-1203
UNCLASS: douglas.molina@va.gov<mailto:douglas.molina@va.gov>
[cid:image002.jpg@01D52CC3.FE488CB0]

**Comment by dmolina213** [comment]
Alexandre on page 8 of your slide deck. how did you get dns showing up on that selection box. On my instance I know I enabled infoblox on the plugin>>enrichment tab. but it never shows up .  Here it is in the enrichment tab
![image](https://user-images.githubusercontent.com/42444130/60463260-1ad42a80-9c11-11e9-90e7-157b21cb37a0.png)


however when I do to the event and click on enrichment i dont see it come up:

![image](https://user-images.githubusercontent.com/42444130/60463327-47884200-9c11-11e9-8662-8343bdc0574a.png)
 Is there a maximum number of modules that I can enable at any given time?

In the meantime, I am going thru the slide deck.

**Comment by dmolina213** [comment]
Inflobox gives us a builder to allow us to see what is the  request being formed ; This is what return when i entered an url.   curl -H "Content-Type":"application/json" -X POST "https://platform.activetrust.net:8000/api/services/intel/lookup/jobs?wait=true" -u <User API Key Inserted Here>: -d '{"target":{"one":{"type": "url","target": "http://whiteelection.com", "sources": ["alexa","atp","dns","gcs","geo","gsb","isight","malware_analysis","pdns","ptr","rwhois","sdf","whois"]}}}' 

Are there existing modules, that i make modifications to, that will do this ?

**Comment by dmolina213** [comment]
I am trying to understand  the slide deck you sent me. My python skills are minimal at best. So if you could kindly explain the following. I am trying to create our own extended module.

In slide # 15 in Extending MISP with Python modules:
1. what is the value of q , if it is not false?
2.Where is the function 'handler' being called ?

**Comment by SteveClement** [comment]
1. Not sure I understand, it is a Boolean, thus it will be True.

2. The 'handler' is called by MISP and MISP expects such a function to be present.
It gets called whenever you trigger the module.

**Comment by dmolina213** [comment]
thank you Steve.
