### ISSUE TITLE
misp-modules requirements not aligned with latest PyMISP?

### ISSUE THREAD

**Issue by juju4** [MISP/misp-modules#314]
It seems misp-modules requirements are not aligned with latest pymisp but on https://github.com/MISP/PyMISP/commit/583fb6592495ea358aad47a8a1ec92d43c13348a from May

When doing install with ansible role, this result in installing recent version and downgrading it after.
```
Found existing installation: pymisp 2.4.111.2\n    Uninstalling pymisp-2.4.111.2:\n      Successfully uninstalled pymisp-2.4.111.2\n  Running setup.py develop for pymisp\n  
```
https://travis-ci.org/juju4/ansible-MISP/jobs/564363442#L5979

Can https://github.com/MISP/misp-modules/blob/master/REQUIREMENTS#L6 be updated to HEAD or newer version? or still work in progress?

else
```
WARNING [api.py:114 - __init__() ] The version of PyMISP recommended by the MISP instance (2.4.111) is newer than the one you're using now (2.4.106). Please upgrade PyMISP.
```
https://travis-ci.org/juju4/ansible-MISP/jobs/564363442#L6330
https://travis-ci.org/juju4/ansible-MISP/jobs/564375031#L6537

Works fine if using older misp-modules tag
https://github.com/MISP/misp-modules/commit/e6f4503763300f5c99a998a3cab58802a9c30b4b
(on centos7 and ubuntu 18.04 - 16.04 seems to have other issues triggered by ExpandedPyMISP and python3.5 only)

Thanks

**Comment by Rafiot** [comment]
Yes, there were lots of changes in PyMISP recently, and the checker on MISP is out of sync.

This will be fixed in the next release (tomorrow, most probably).

**Comment by juju4** [comment]
Latest build fine https://travis-ci.org/juju4/ansible-MISP with https://github.com/MISP/misp-modules/commit/500d4c14c06f5eff7efbde0a666adb8db8d083ca

Thanks!
