### ISSUE TITLE
csvimport parsing csv twice?

### ISSUE THREAD

**Issue by zaphodef** [MISP/misp-modules#325]
When importing a simple csv (`1.2.3.4, example.com` with headers `ip-src,domain`), the module fails with the error `AttributeError: 'list' object has no attribute 'split'` line 88. It looks like csvimport is parsing the csv twice, as removing [line 207](https://github.com/MISP/misp-modules/blob/696bafa749da1cbc0866f332ab801bd90fe06962/misp_modules/modules/import_mod/csvimport.py#L207) fixes the issue.

**Comment by chrisr3d** [comment]
I updated the module a couple of weeks ago (+ a small fix today), it should be working now I will close the issue, but please reopen if needed
