### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by todonaki** [MISP/misp-modules#349]
I've been trying without success  to import **ANY** data through the Csvimport module.
I created a test event and then choose "Populate from..." in the options for the event.
I choose the Csvimport option which I successfully enabled through settings.

I have a very simple CSV file with two columns.  They have the headers ip-src,domain.
I tick the box Has_header, load the file, and press Import.

In the GUI I get "Something went wrong, look in the server logs for details" and "Results from the enrichment module for this attribute are empty." for the import results.

In STDOUT from the terminal window, I get the following error:

> ERROR:misp-modules:Something went wrong:
> Traceback (most recent call last):
> File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/var/www/MISP/venv/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 222, in handler
    csv_parser = CsvParser(header, has_header, data)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 49, in __init__
    self.parse_data(data)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 81, in parse_data
    line = line.split('#')[0].strip()
AttributeError: 'list' object has no attribute 'split'

I have no idea what I'm doing wrong (if anything) or if there's an real error with my MISP setup  that I need to address.  I've found others that seem to have similar problems, but I have not seen a resolution to the problem.

**Please**, help me to find a resolution...  **Thank you!**

**Comment by chrisr3d** [comment]
I updated this module recently, and looking at the error message it looks like you have a pretty old version.
Can you update your misp modules repository and test again after you make sure you restart misp-modules with the correct version ? ([Here is a small reminder on how to do it](https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules-in-a-python-virtualenv-recommended) if needed)

**Comment by todonaki** [comment]
**Thank you!**  That seems to have corrected my CSV import problem perfectly
