### ISSUE TITLE
Installation seems incomplete

### ISSUE THREAD

**Issue by SourceCodeDeleted** [MISP/misp-modules#354]
Good day 
I am running this one Ubuntu 18.04 . and I noticed that it seems that the MISP modules are telling me connection refused.

The instructions I used to install are from [here](https://misp.github.io/MISP/INSTALL.ubuntu1804/)

Since this cannot be done as root, I run as **misp** user

> wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M

When logging into the diagnostics I see this...

```
Enrichment module system…Connection refused
Import module system…Connection refused
Export module system…Connection refused
Cortex module system…System not enabled
```

When I try to launch the MISP module service using 
`/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & #to start the modules
`

I receive the following.  Keep in mind that I have tried to run this as the misp user and I receive the same output. 

```
root@misp:/tmp# ps aux|grep -i pythonNo module named 'misp_modules.modules.expansion._ransomcoindb'
2019-11-29 07:24:56,844 - misp-modules - INFO - Launch MISP modules server from package.
INFO:misp-modules:Launch MISP modules server from package.
2019-11-29 07:24:56,847 - misp-modules - INFO - Helper loaded cache
INFO:misp-modules:Helper loaded cache
2019-11-29 07:24:56,847 - misp-modules - INFO - Unable to load MISP modules from package.
INFO:misp-modules:Unable to load MISP modules from package.
^C
```

I have gone through many things and have even reinstalled the whole container to come back to this problem. 

**How can I resolve this problem?**
 I understand this python lib needs to be installed , but from where? It looks like this is a local lib specific to this project.

**Comment by juju4** [comment]
same here
https://travis-ci.org/juju4/ansible-MISP/jobs/622185202#L6591 but only on Ubuntu 18.04 and not Centos7 strangely (https://travis-ci.org/juju4/ansible-MISP/jobs/622185203#L11130)

part of https://github.com/MISP/misp-modules/pull/353

**Comment by SourceCodeDeleted** [comment]
Ironically I was able to get around this using just the command and not adding parameters. 

`/var/www/MISP/venv/bin/misp-modules`

**Comment by phage-nz** [comment]
I dropped a __init__.py into /usr/local/src/misp-modules/misp_modules/modules/expansion/_ransomcoindb then rebuilt the virtualenv (as per install.sh, which I used to build a new instance a few days ago):
```
cd /usr/local/src/misp-modules
sudo chgrp www-data .
sudo chmod g+w .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
sudo chgrp staff .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I .
```
Now get this:
```
Feb 17 23:06:43 misp systemd[1]: Started System-wide instance of the MISP Modules.
Feb 17 23:06:46 misp misp-modules[19828]: Unable to import URLObject, pyfaup missing
Feb 17 23:06:46 misp misp-modules[19828]: 2020-02-17 23:06:46,125 - misp-modules - INFO - Launch MISP modules server from package.
Feb 17 23:06:46 misp misp-modules[19828]: INFO:misp-modules:Launch MISP modules server from package.
Feb 17 23:06:46 misp misp-modules[19828]: 2020-02-17 23:06:46,128 - misp-modules - INFO - Helper loaded cache
Feb 17 23:06:46 misp misp-modules[19828]: INFO:misp-modules:Helper loaded cache
Feb 17 23:06:46 misp misp-modules[19828]: 2020-02-17 23:06:46,128 - misp-modules - INFO - Unable to load MISP modules from package.
Feb 17 23:06:46 misp misp-modules[19828]: INFO:misp-modules:Unable to load MISP modules from package.
```
Unsure if it's a step forward or step back.

**Comment by NailBash** [comment]
I just created empty __init__.py file in misp_modules/modules/expansion/_ransomcoindb folder, then started by 'systemctl start misp-modules' and everything is work now.
thanks to https://github.com/MISP/misp-modules/pull/373

**Comment by srikwit** [comment]
The issue is still persistent on non-Docker setup (system install).
