### ISSUE TITLE
[cve] Support CVE in Object

### ISSUE THREAD

**Issue by mokaddem** [MISP/misp-modules#372]
CVE defined in Object cannot be expanded using the enrichment because the Attribute type is `text` instead of `vulnerability`.
It should support `text` or change the Object template

**Comment by NomisRenarc** [comment]
good day team, has anyone looked into this yet?

I would like to use this feature as well.

regards

**Comment by adulau** [comment]
Which object template? The vulnerability object seems correct to me https://github.com/MISP/misp-objects/blob/main/objects/vulnerability/definition.json#L33

**Comment by NomisRenarc** [comment]
> Which object template? The vulnerability object seems correct to me https://github.com/MISP/misp-objects/blob/main/objects/vulnerability/definition.json#L33

thanks for that, I am using a container build of MISP which is still 2.4.133, presume the above mentioned fix is in a build after that?

**Comment by adulau** [comment]
Indeed but don't forget to do a `git submodule update` and update the object in the UI to have the latest version of the objects.

**Comment by NomisRenarc** [comment]
thanks for the assistance.
played around a little with building MISP and got the CVE module under
build 2.4.136 to work.

**Comment by adulau** [comment]
Perfect. I'll close the issue then.
