### ISSUE TITLE
Errors trying to install 2.4.125 MISP modules

### ISSUE THREAD

**Issue by clopmz** [MISP/misp-modules#396]
Hi all,

 Launching the following command to install 2.4.125 misp-modules returns the following errors:

root@misp01-srv:/usr/local/src/misp-modules# sudo -H -u apache -g apache /var/www/MISP/venv/bin/pip --proxy http://proxy.mydom.com:8080 install -U -I -r REQUIREMENTS
Obtaining file:///usr/local/src/misp-modules (from -r REQUIREMENTS (line 2))
Obtaining pybgpranking from git+https://github.com/D4-project/BGP-Ranking.git/@fd9c0e03af9b61d4bf0b67ac73c7208a55178a54#egg=pybgpranking&subdirectory=client (from -r REQUIREMENTS (line 3))
  Skipping because already up-to-date.
Obtaining pyipasnhistory from git+https://github.com/D4-project/IPASN-History.git/@fc5e48608afc113e101ca6421bf693b7b9753f9e#egg=pyipasnhistory&subdirectory=client (from -r REQUIREMENTS (line 4))
  Skipping because already up-to-date.
Obtaining pyintel471 from git+https://github.com/MISP/PyIntel471.git@0df8d51f1c1425de66714b3a5a45edb69b8cc2fc#egg=pyintel471 (from -r REQUIREMENTS (line 5))
  Skipping because already up-to-date.
Obtaining pymisp[fileobjects,openioc,pdfexport,virustotal] from git+https://github.com/MISP/PyMISP.git@b5b40ae2c5225a4b349c26294cfc012309a61352#egg=pymisp[fileobjects,openioc,virustotal,pdfexport] (from -r REQUIREMENTS (line 6))
  Skipping because already up-to-date.
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /var/www/MISP/venv/bin/python3 /var/www/MISP/venv/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-em47imrl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe583254940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/poetry/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe583257588>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/poetry/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe583257748>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/poetry/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe5832576d8>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/poetry/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe5832572e8>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/poetry/
  ERROR: Could not find a version that satisfies the requirement poetry>=0.12 (from versions: none)
  ERROR: No matching distribution found for poetry>=0.12
  ----------------------------------------
ERROR: Command errored out with exit status 1: /var/www/MISP/venv/bin/python3 /var/www/MISP/venv/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-em47imrl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12' Check the logs for full command output.

 As you can see, I need to configure a proxy to download all modules. I have setup http_proxy and https_proxy env variables also without luck ...

Any idea?

**Comment by rishab-rb** [comment]
Hey, I installed MISP using Vagrant, most of the docker images seemed to be broken.
I don't have misp-modules in the web platform.
Please help.
In the last stages of installation, these are the logs for misp-modules:

default: --- Installing MISP modules… ---
    default: Cloning into 'misp-modules'...
    default:   Could not find a tag or branch 'fd9c0e03af9b61d4bf0b67ac73c7208a55178a54', assuming commit.
    default:   Could not find a tag or branch 'fc5e48608afc113e101ca6421bf693b7b9753f9e', assuming commit.
    default:   Could not find a tag or branch '0df8d51f1c1425de66714b3a5a45edb69b8cc2fc', assuming commit.
    default:   Could not find a tag or branch 'b5b40ae2c5225a4b349c26294cfc012309a61352', assuming commit.
    default:   Could not find a tag or branch '411572840eba4c72dc321c549b36a54ed5cea9de', assuming commit.
    default:   Could not find a tag or branch '49d6938693f6faa3ff09998f86dba551ae3a996b', assuming commit.
    default:   Could not find a tag or branch '48c1f740025c51289f43a24863d1845ff12fd21a', assuming commit.
    default:   Could not find a tag or branch '1ce15581beebb13e841193a08a2eb6f967855fcb', assuming commit.
    default:   Failed building wheel for pdftotext
    default:   Failed building wheel for pydeep
    default: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nw55cl7w/pydeep/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6_uhfkhg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nw55cl7w/pydeep/

**Comment by adulau** [comment]
You should try to install the misp-modules directly as described in the README file.
