### ISSUE TITLE
liblua 5.3 dependency

### ISSUE THREAD

**Issue by Golbark** [MISP/misp-modules#398]
Hi all,
I'm installing misp-modules on RHEL 7 and when I want to run it, a fair portion of the modules are not loaded due to liblua-5.3.so not being on the system. Unfortunately with RHEL, I can only get lua 5.1. 

This is the exact error message:
WARNING: MISP modules apivoid failed due to liblua-5.3.so: cannot open shared object file: No such file or directory

As the relation between these modules and lua is not straightforward, I was wondering if you knew about this and if there are any workaround?

**Comment by adulau** [comment]
Interesting. It's indeed quite strange but it seems all the modules with the issue depends on PyMISP.

**Comment by adulau** [comment]
Ok it's faup which requires lua. Basically, misp-modules -> PyMISP -> faup then lua shared libary ;-)

**Comment by Rafiot** [comment]
@Golbark if you update PyMISP to the latest version on github, you will have a fix. Otherwise, just modify the installed package manually, it is a one liner change.

**Comment by Rafiot** [comment]
Related issue upstream: https://github.com/stricaud/faup/issues/110

**Comment by Golbark** [comment]
Thanks for the quick replies! I confirm the fix works.
