### ISSUE TITLE
liblua-5.3.so error

### ISSUE THREAD

**Issue by Rickozono** [MISP/misp-modules#399]
Hi, I having troubles instaling the misp modules, in several modules the output is the following:
MISP modules "XXXX" failed due to liblua-5.3.so: cannot open shared object file: No such file or directory
Any ideas how to fix this error?
Thank you for any help

**Comment by adulau** [comment]
https://github.com/MISP/misp-modules/issues/398 it's fixed in PyMISP. and faup will fix the issue upstream soon.
