### ISSUE TITLE
Using modules

### ISSUE THREAD

**Issue by Rickozono** [MISP/misp-modules#400]
I was trying to use misp-modules, but I can't.
The module I tried is greynoise.
This is the information of the log file:
 File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.greynoise.io', port=8888): Max retries exceeded with url: /v1/query/ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9847997f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Any ideas, how to solve it?
Thanks for any reply

**Comment by chrisr3d** [comment]
I wanted to test this module to try to reproduce your issue, but I only got some HTTP 429 error meaning I reached the number of requests limit. Then I realized it changed and switched to a new version of API.
So I update the module to follow those changes.

If you want to give it a try, just be aware that a Greynoise API key is required.
Let me know if you have any question or issue

**Comment by adulau** [comment]
This should have been fixed in recent version of the MISP modules. Feel free to reopen if the issue persists.
