### ISSUE TITLE
joesandbox_submit module not working

### ISSUE THREAD

**Issue by vsantola** [MISP/misp-modules#410]
Hi guys,

the joesandbox submit module is not working, the request["data"] is always empty when the attribute is of type malware-sample or attachment and the following expection triggers:

> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: 2020-06-30 15:42:55,586 - misp-modules - ERROR - Something went wrong:
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: Traceback (most recent call last):
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     value = future.result()
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     result = self.fn(*self.args, **self.kwargs)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     response = mhandlers[x['module']].handler(q=jsonpayload)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/expansion/joesandbox_submit.py", line 83, in handler
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     data = _decode_malware(request.get("data"), True)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/expansion/joesandbox_submit.py", line 117, in _decode_malware
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     data = base64.b64decode(data)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/base64.py", line 80, in b64decode
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     s = _bytes_from_decode_data(s)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     "string, not %r" % s.__class__.__name__) from None
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: ERROR:misp-modules:Something went wrong:
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: Traceback (most recent call last):
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     value = future.result()
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     result = self.fn(*self.args, **self.kwargs)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     response = mhandlers[x['module']].handler(q=jsonpayload)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/expansion/joesandbox_submit.py", line 83, in handler
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     data = _decode_malware(request.get("data"), True)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/expansion/joesandbox_submit.py", line 117, in _decode_malware
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     data = base64.b64decode(data)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/base64.py", line 80, in b64decode
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     s = _bytes_from_decode_data(s)
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:   File "/var/www/MISP/venv/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]:     "string, not %r" % s.__class__.__name__) from None
> Jun 30 15:42:55 ip-misp-01 misp-modules[14194]: TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
> 

This is a fresh install of MISP-cloud for testing purposes, running MISP 2.4.128 and misp-modules cloned today from github.
From what i can see requests['data'] is always empty on this and any other module that submit samples. Can someone shed some lights, maybe an update somewhere that broke this?

Thanks.

**Comment by vsantola** [comment]
Ok, found my own answer. Adding module format as misp_standard and changing some code will work. Will add a PR in a bit.

**Comment by adulau** [comment]
Thank you!

**Comment by adulau** [comment]
Any news for the pull-request? or this was fixed in the mean time? I'll close the issue for the time being.
