### ISSUE TITLE
Querying modules issues

### ISSUE THREAD

**Issue by Batata-ops** [MISP/misp-modules#412]
I've been running into some issues with Misp-modules
I'm following the documentation on Github and when I test my modules I get the right results BUT
whenever I " curl -s http://127.0.0.1:6666/query -H "Content-Type: application/json" --data @body.json -X POST " **or** " curl -s http://127.0.0.1:6666/query --header "Authorization: <API Key>" --header "Accept: application/json" --header "Content-Type: application/json" --data @body.json -X POST" as stated in the doc (checking for the dns modules) I get the following: "{"error": "Something went wrong, look in the server logs for details"} "
I check my Syslog and this is the result I constantly see : 
<img width="1167" alt="Screen Shot 2020-07-07 at 4 33 00 PM" src="https://user-images.githubusercontent.com/68103259/87428760-822a0600-c5eb-11ea-8f94-2a18ed5b281e.png">

the content of body.json is as follows: `{"module": "dns", "hostname" : "www.circl.lu" ,"config" :{"nameserver" : "8.8.8.8"}}`
bodypassivetotal.json doesn't work either

**Comment by chrisr3d** [comment]
Hi,
This error comes from the python json library that is not able to load the file passed as parameter.

Did you try with the `body.json` that is within the [tests](https://github.com/MISP/misp-modules/tree/main/tests) directory?
To start with the most obvious reason of failure I see here: can you try to pass the full path of the file?
```
cd /usr/local/src/misp-modules
curl -s http://127.0.0.1:6666/query -H "Content-Type: application/json" --data @tests/body.json -X POST
```
Or alternatively replace with the absolute path of you `body.json` file if needed (for instance if your misp-modules repository is not installed within `/usr/local/src/misp-modules`)

Hope it helps, but let me know if you already tried with different paths and got the same issue, or if you first try now and it still fails

**Comment by adulau** [comment]
Feel free to reopen the issue if the issue is not solved.
