### ISSUE TITLE
Any reason why we're still at release v2.4.121?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-modules#419]
cf. #378

**Comment by StefanKelm** [comment]
Apologies for nagging, guys, but why are misp-modules not in line with MISP wrt the release number?
Our current update process only pulls new releases which means that our misp-modules are stuck in February although our MISP version is current...

**Comment by adulau** [comment]
Indeed, we will re-tag it to the latest version. The current workflow is to re-tag when there are major changes but we could do it at each MISP core release.

**Comment by StefanKelm** [comment]
Thanks a lot! :-)

**Comment by chrisinmtown** [comment]
Yes, please tag misp-modules at each major MISP release.

**Comment by chrisinmtown** [comment]
Do you think you might dig thru the history and add some tags for recent MISP releases, maybe at least 2.4.133 and 2.4.134?
