### ISSUE TITLE
Installing custom module require me to change __init__.py

### ISSUE THREAD

**Issue by BrunoMCBraga** [MISP/misp-modules#421]
Hello fellas

I have developed a custom module for MISP and i noticed that when i copy it to the folder: /usr/local/src/misp-modules/misp_modules/modules/expansion it does not show up on the list of modules.

I have to do (usr/local/src/misp-modules/misp_modules/modules/expansion/__init__.py):
...

__all__ = [..., 'mymodule']

...

Is this necessary or am i missing something?

**Comment by adulau** [comment]
Yes it's a necessary step.
