### ISSUE TITLE
The email importer module passes an inproper value to the EMailObject

### ISSUE THREAD

**Issue by seamustuohy** [MISP/misp-modules#427]
On line 45 of the email import it passes `attach_original_mail` to EMailObject. This doesn't currently impact the code as the default  value for this is set to True. That said, it could lead to unexpected results in the future. The appropriate value should be `attach_original_email`.

https://github.com/MISP/misp-modules/blob/ae1016946bbbe0dd2652e0c383b8c5214fca4527/misp_modules/modules/import_mod/email_import.py#L45

**Comment by Rafiot** [comment]
Woops, good catch, thank you!
