### ISSUE TITLE
failed due to __init__() got an unexpected keyword argument 'requote'

### ISSUE THREAD

**Issue by pettai** [MISP/misp-modules#434]
After (re)installing misp-modules from scratch on a Ubuntu 18.04, following the misp-modules guide
https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules-in-a-python-virtualenv-recommended

misp-modules won't start in venv as www-data

```
root@server:~# sudo -u www-data /var/www/MISP/venv/bin/misp-modules -d -l 127.0.0.1 -s
__init__() got an unexpected keyword argument 'requote'
2020-10-21 13:35:59,786 - misp-modules - INFO - Launch MISP modules server from package.
2020-10-21 13:35:59,788 - misp-modules - INFO - Helper loaded cache
2020-10-21 13:35:59,788 - misp-modules - INFO - Unable to load MISP modules from package.
```

Adding --devel to the command-line, makes misp-modules run, and it also echoes the following warnings:

```
root@misp:~# sudo -u www-data /var/www/MISP/venv/bin/misp-modules -d -l 127.0.0.1 --devel
__init__() got an unexpected keyword argument 'requote'
2020-10-21 13:36:13,954 - misp-modules - INFO - Launch MISP modules server in developement mode. Enable debug, load a list of modules is -m is used.
2020-10-21 13:36:13,955 - misp-modules - INFO - Launch MISP modules server from current directory.
2020-10-21 13:36:13,956 - misp-modules - INFO - Helpers loaded cache.py
[...]
2020-10-21 13:36:14,604 - misp-modules - WARNING - MISP modules assemblyline_query failed due to __init__() got an unexpected keyword argument 'requote'
WARNING:misp-modules:MISP modules assemblyline_query failed due to __init__() got an unexpected keyword argument 'requote'
[...]
2020-10-21 13:36:14,741 - misp-modules - WARNING - MISP modules assemblyline_submit failed due to __init__() got an unexpected keyword argument 'requote'
WARNING:misp-modules:MISP modules assemblyline_submit failed due to __init__() got an unexpected keyword argument 'requote'
[...]
2020-10-21 13:36:14,805 - misp-modules - WARNING - MISP modules domaintools failed due to __init__() got an unexpected keyword argument 'requote'
WARNING:misp-modules:MISP modules domaintools failed due to __init__() got an unexpected keyword argument 'requote'
[...]
2020-10-21 13:36:14,820 - misp-modules - INFO - MISP modules server started on 127.0.0.1 port 6666
INFO:misp-modules:MISP modules server started on 127.0.0.1 port 6666
2020-10-21 13:38:02,752 - misp-modules - DEBUG - MISP ListModules request
DEBUG:misp-modules:MISP ListModules request
^C
```

**Comment by digihash** [comment]
I have the same issue after update the misp-modules with a git pull to main today.

**Comment by adulau** [comment]
Could you verify which version of yarl is installed? I did some tests on the latest HEAD with yarl 1.6.0 and Python 3.6.9 and it works as expected.

**Comment by pettai** [comment]
My styff is up-to-date:

```
root@misp:/var/www/MISP# sudo -u www-data /var/www/MISP/venv/bin/pip list|grep yarl
yarl                   1.6.0

root@misp:/var/www/MISP# dpkg -l |  grep " python3.6 "
ii  python3.6                          3.6.9-1~18.04ubuntu1.3                      amd64        Interactive high-level object-oriented language (version 3.6)
```

Side note: I tried do everything the guide says without using an virtualenv, and that works (I don't get the 'requote' problem)
(all python3 pip package versions are on par in both the virtual env and without the venv)

**Comment by digihash** [comment]
I'm using the venv and in there I have yarl 1.6.0 and Python 3.7.3, but I get the requote thing.

**Comment by kuselfoo** [comment]
I had the same issue on a fresh Ubuntu 18.04 with yarl 1.6.0 and python 3.6.9 when following the recommended installation guide for misp-modules, but I could resolve it by upgrading pip.
What I did was:
```
sudo killall misp-modules
sudo rm -rf /var/www/MISP/venv
sudo -u www-data python3 -m venv /var/www/MISP/venv
sudo -u www-data /var/www/MISP/venv/bin/pip install --upgrade pip
sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
sudo -u www-data /var/www/MISP/venv/bin/pip install .
sudo systemctl start misp-modules
```

**Comment by adulau** [comment]
@digihash @pettai Could you confirm that the update of pip solved your issue too? It's indeed weird.

**Comment by pettai** [comment]
I tried it without deleting the old venv, and that didn't solve it.

**Comment by digihash** [comment]
For me it worked by following the procedure from @kuselfoo and then installing Fauv using the steps on the bottom of this comment: https://github.com/MISP/misp-modules/issues/354#issuecomment-586918877

**Comment by digihash** [comment]
Without deleting the old venv, it didn't work. Maybe some corruption of the venv over time, I don't know.

**Comment by adulau** [comment]
I'll close the issue as it seems related to Python and a cleaning up of the venv solved the issue. Thanks for the reports and tests.
