### ISSUE TITLE
error: could not create 'misp_modules.egg-info': Permission denied

### ISSUE THREAD

**Issue by B1u3f331** [MISP/misp-modules#441]
I am following the below steps to install MISP: 
"
How to install and start MISP modules in a Python virtualenv? (recommended)
sudo apt-get install python3-dev python3-pip libpq5 libjpeg-dev tesseract-ocr libpoppler-cpp-dev imagemagick virtualenv libopencv-dev zbar-tools libzbar0 libzbar-dev libfuzzy-dev build-essential -y
sudo -u www-data virtualenv -p python3 /var/www/MISP/venv
cd /usr/local/src/
chown -R www-data .
sudo git clone https://github.com/MISP/misp-modules.git
cd misp-modules
sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
sudo -u www-data /var/www/MISP/venv/bin/pip install .
# Start misp-modules as a service
sudo cp etc/systemd/system/misp-modules.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now misp-modules
/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & #to start the modules
"

but I got error in this setp:

“sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS”

the error shows 
![image](https://user-images.githubusercontent.com/28138784/98627095-58d97680-234e-11eb-848b-62db88cc6afb.png)

![image](https://user-images.githubusercontent.com/28138784/98626955-eec0d180-234d-11eb-87ef-0691e14f433c.png)

**Comment by adulau** [comment]
As indicated, you have some permissions issues in your directory. I would do a `chown` to www-data for the directory having issues.
