### ISSUE TITLE
Unable to load MISP modules from package

### ISSUE THREAD

**Issue by B1u3f331** [MISP/misp-modules#444]
I downloaded the VM from below link:
https://www.misp-project.org/download/
https://www.circl.lu/misp-images/latest/

I follow the steps to download and install modules.

but final step,  /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & #to start the modules
it got this error, Unable to load MISP modules from package
![image](https://user-images.githubusercontent.com/28138784/98905034-ad6b2600-24f5-11eb-9c8a-3a199f7c061a.png)

**Comment by B1u3f331** [comment]
Problem sovled. it need install additional moudles censys, pyfaup
/var/www/MISP/venv/bin/pip install censys
/var/www/MISP/venv/bin/pip install pyfaup

**Comment by chrisinmtown** [comment]
Right, but why close this without action? Should censys and pyfaup be added to the REQUIREMENTS file?
