### ISSUE TITLE
Unable to load MISP modules from package -  No module named 'dnsdb2'

### ISSUE THREAD

**Issue by fipe-ch** [MISP/misp-modules#449]
Hey

We have install the modules. But we can't load the modules

sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & 
 No module named 'dnsdb2'

2020-11-26 11:24:32,755 - misp-modules - INFO - Launch MISP modules server from package.
2020-11-26 11:24:32,756 - misp-modules - INFO - Helper loaded cache
2020-11-26 11:24:32,756 - misp-modules - INFO - Unable to load MISP modules from package.
^C
[1]+  Done                    sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s

We can't find a modul named dnsdb2.

Module System
This tool tests the various module systems and whether they are reachable based on the module settings.

Enrichment module system…Connection refused
Import module system…Connection refused
Export module system…Connection refused
Cortex module system…Connection refused

Thank you for your help

Fipe

**Comment by adulau** [comment]
It seems that dnsdb2 is not installed. Could you run a `pip3 install dnsdb2`?

**Comment by fipe-ch** [comment]
Hi have execute pip3 install dnsdb2

But i receive the same error 
sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & 
No module named 'dnsdb2'
2020-11-26 14:21:26,465 - misp-modules - INFO - Launch MISP modules server from package.
2020-11-26 14:21:26,466 - misp-modules - INFO - Helper loaded cache
2020-11-26 14:21:26,466 - misp-modules - INFO - Unable to load MISP modules from package.

**Comment by adulau** [comment]
did you install dnsdb2 in the venv ?

**Comment by fipe-ch** [comment]
I'm not sure what you mean.
I have execute the command. when i execute the command a second time 
pip3 install dnsdb2
Requirement already satisfied: dnsdb2 in /home/secuser/.local/lib/python3.8/site-packages (1.1.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from dnsdb2) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->dnsdb2) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->dnsdb2) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->dnsdb2) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->dnsdb2) (1.25.10)

**Comment by adulau** [comment]
Just enable the Python venv and do the install within it.

**Comment by fipe-ch** [comment]
I have newly installed misp. 
sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & 
Now outputs the following errors.
misp@bivimgm049:~$ No module named '_vmray.vmray_rest_api'.
2020-12-04 07:15:50,320 - misp-modules - INFO - Launch MISP modules server from package.
2020-12-04 07:15:50,321 - misp-modules - INFO - Helper loaded cache
2020-12-04 07:15:50,321 - misp-modules - INFO - Unable to load MISP modules from package.
 
I saw that the module was changed a few days ago. Something is probably wrong here 

Thanks for the help

Translated with www.DeepL.com/Translator (free version)

**Comment by chrisinmtown** [comment]
You probably should post the tag or git commit hash that you used for misp-modules.  I see that dnsdb2 was not listed in the file REQUIREMENTS in the version tagged v2.4.134, but is in there as of commit ed5a43222264e17aa69de4a6b06de5fce7d945b7 dated 27 Nov 2020.

**Comment by NoDataFound** [comment]
@fipe-ch  It hasn't been merged yet, but you can try this PR locally and see if it resolves your issue. https://github.com/MISP/misp-modules/pull/466

**Comment by chrisinmtown** [comment]
https://github.com/MISP/misp-modules/issues/458 also documents a problem with missing module vmray-something

**Comment by chrisinmtown** [comment]
PR #466 has been merged

**Comment by adulau** [comment]
Feel free to reopen the issue if this is not fixed in recent version (v2.4.141). Thank you.
