### ISSUE TITLE
Add compatible misp-modules version to existing MISP installation?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#454]
Please clarify the installation instructions regarding versions. What version of misp-modules should be installed into an existing MISP?  For example if we're running MISP ver 2.4.133, what tag should we checkout when installing misp-modules? 

I was a little surprised to see very few version tags in the misp-modules repo, far fewer than over in MISP. I cannot simply checkout version 2.4.133 of misp-modules bcos that tag is not available. The installation instructions just say "git clone" blah blah which of course puts us right at the tip of the bleeding edge of branch main, and given that the build is currently failing, that might be a bit too uncooked for us.  

Thanks in advance.

**Comment by StefanKelm** [comment]
Somewhat related to what we've discussed in #419 ;-)

**Comment by chrisinmtown** [comment]
Thanks, I searched for similar issues but failed to find that one, sorry to create a dupe.
