### ISSUE TITLE
When a new release is published, include  "Latest release"

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-modules#456]
When a new release is published, apart from the versioning tag, also have the Latest release available via /releases/latest

**Comment by cudeso** [comment]
https://github.com/MISP/misp-modules/issues/419 is also related

**Comment by adulau** [comment]
Done. Starting from MISP modules v2.4.141, we use the release of GitHub. [latest release](https://github.com/MISP/misp-modules/releases).

Thank you!
