### ISSUE TITLE
No module named '_vmray.vmray_rest_api'

### ISSUE THREAD

**Issue by dpreuveneers** [MISP/misp-modules#458]
When starting the MISP modules, I get an error: No module named '_vmray.vmray_rest_api'

The module [vmray_submit.py](https://github.com/MISP/misp-modules/blob/main/misp_modules/modules/expansion/vmray_submit.py) has the following import statement:

`from _vmray.vmray_rest_api import VMRayRESTAPI`

After the recent updates of the VMRay module and the file renaming in commit 2a870f2, I believe this import statement should become:

`from _vmray.rest_api import VMRayRESTAPI`

**Comment by chrisinmtown** [comment]
Please test again, should be fixed now that PR #466 has been merged

**Comment by dpreuveneers** [comment]
Just reinstalled MISP on Ubuntu 20.04, and this VMRay issue seems to be resolved.
