### ISSUE TITLE
Conflict version

### ISSUE THREAD

**Issue by adulau** [MISP/misp-modules#459]
`
The conflict is caused by:
    The user requested validators==0.14.0
    apiosintds 1.8.3 depends on validators==0.14.0
    pymisp[fileobjects,openioc,pdfexport,virustotal] 2.4.123 depends on validators<0.15.0 and >=0.14.2; extra == "virustotal"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
`

**Comment by dhaef** [comment]
I'm currently getting this error when I run `sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS`

Is there a fix for this?

**Comment by GlennHD** [comment]
> I'm currently getting this error when I run `sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS`
> 
> Is there a fix for this?

I think it's safe to ignore. The DigitalSide fellas have to fix their dependency I'd imagine. https://github.com/davidonzo/apiosintDS/blob/master/requirements.txt
