### ISSUE TITLE
Install instructions for RHEL should list prereq package rh-python36

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#460]
The README.md section "How to install and start MISP modules on RHEL-based distributions" assumes that rh-python36 is installed (invocation of scl) but does not list a yum command to install it.  If rh-python36 must be used in the scl command, then I suggest that the first line:

https://github.com/MISP/misp-modules/blob/58bac998c0338d7d929360262ae815965cb1d16d/README.md#L150

Be changed to this:
```
sudo yum install rh-python36 rh-ruby22
```
If rh-python36 is NOT required, then please reword the directions to skip it, it appears here:

https://github.com/MISP/misp-modules/blob/58bac998c0338d7d929360262ae815965cb1d16d/README.md#L156

and here:

https://github.com/MISP/misp-modules/blob/58bac998c0338d7d929360262ae815965cb1d16d/README.md#L171

**Comment by chrisinmtown** [comment]
I propose this minor change:
```
diff --git a/README.md b/README.md
index 67573da..72fde4a 100644
--- a/README.md
+++ b/README.md
@@ -142,7 +142,7 @@ sudo systemctl enable --now misp-modules
 As of this writing, the official RHEL repositories only contain Ruby 2.0.0 and Ruby 2.1 or higher is required. As such, this guide installs Ruby 2.2 from the [SCL](https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.2_release_notes/chap-installation#sect-Installation-Subscribe) repository. 
 
 ~~~~bash
-sudo yum install rh-ruby22
+sudo yum install rh-python36 rh-ruby22
 sudo yum install openjpeg-devel
 sudo yum install rubygem-rouge rubygem-asciidoctor zbar-devel opencv-devel gcc-c++ pkgconfig poppler-cpp-devel python-devel redhat-rpm-config
 cd /var/www/MISP
```

**Comment by chrisinmtown** [comment]
Does anyone monitor this issue board?

**Comment by adulau** [comment]
Updated
