### ISSUE TITLE
New misp-modules tag 2.4.146 is WAY ahead of MISP on purpose?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#467]
happy new year, I don't mean to waste your time but just want to check, did you really mean to add tag 2.4.146 in misp-modules? The MISP repo's latest tag is 2.4.136.

**Comment by chrisinmtown** [comment]
CIRCL team, what is the right way to ask trivial questions like this? Apparently github issues are not the best approach?

**Comment by StefanKelm** [comment]
You may want to give https://gitter.im/MISP/Support a try?

**Comment by chrisinmtown** [comment]
I will try that, but it's a little touchy becos that site is completely blocked by my corporate web proxy. :/

**Comment by chrisinmtown** [comment]
gitter works :)

> Andras Iklody
> @iglocska
> 10:40
> that is definitely a typo
> off by one (someone incremented the wrong number)

**Comment by adulau** [comment]
Tag removed. Tagged with v2.4.137.

Thanks for the notification.
