### ISSUE TITLE
ERROR: Service 'misp-modules' failed to build:

### ISSUE THREAD

**Issue by chandan8893** [MISP/misp-modules#469]
Hi Team,

I am trying to build the misp-module container, but ending up with the error.

MISP_TAG=v2.4.133
MODULES_TAG=v2.4.134
PHP_VER=20180731

Below is the error.

**Step 7/14 : RUN git clone --branch ${MODULES_TAG} --depth 1  https://github.com/MISP/misp-modules.git /srv/misp-modules;         cd /srv/misp-modules || exit; sed -i 's/-e //g' REQUIREMENTS; pip3 wheel -r REQUIREMENTS --no-cache-dir -w /wheel/
 ---> Running in 3ba61affd3f8
Cloning into '/srv/misp-modules'...
Note: checking out '6e93622174225051afb444f98dfdfd53f6bab28f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Ignoring idna-ssl: markers 'python_version < "3.7"' don't match your environment
Processing /srv/misp-modules
Collecting pybgpranking
  Cloning https://github.com/D4-project/BGP-Ranking.git/ (to revision fd9c0e03af9b61d4bf0b67ac73c7208a55178a54) to /tmp/pip-wheel-uvfcvufd/pybgpranking_4bad5f0cb36c413287735fe8eab0fe68
Collecting pyipasnhistory
  Cloning https://github.com/D4-project/IPASN-History.git/ (to revision fc5e48608afc113e101ca6421bf693b7b9753f9e) to /tmp/pip-wheel-uvfcvufd/pyipasnhistory_0309bc5c45604aa3b1e51f60b6e545a8
Collecting pyintel471
  Cloning https://github.com/MISP/PyIntel471.git (to revision 0df8d51f1c1425de66714b3a5a45edb69b8cc2fc) to /tmp/pip-wheel-uvfcvufd/pyintel471_637e85dc7b9b48058082d1b8bb766fd5
Collecting pymisp[fileobjects,openioc,pdfexport]
  Cloning https://github.com/MISP/PyMISP.git (to revision bacd4c78cd83d3bf45dcf55cd9ad3514747ac985) to /tmp/pip-wheel-uvfcvufd/pymisp_f34e600d9f79400cadd5fd210d9ea1f9
ERROR: Command errored out with exit status 128: git clone -q https://github.com/MISP/PyMISP.git /tmp/pip-wheel-uvfcvufd/pymisp_f34e600d9f79400cadd5fd210d9ea1f9 Check the logs for full command output.
ERROR: Service 'misp-modules' failed to build: The command '/bin/sh -c git clone --branch ${MODULES_TAG} --depth 1  https://github.com/MISP/misp-modules.git /srv/misp-modules;         cd /srv/misp-modules || exit; sed -i 's/-e //g' REQUIREMENTS; pip3 wheel -r REQUIREMENTS --no-cache-dir -w /wheel/' returned a non-zero code: 1
**

**Comment by chandan8893** [comment]
Can someone please help me fixing the issue

**Comment by chrisinmtown** [comment]
Your build hardly got started, it failed with a git-clone error, so I believe you'll have to figure this out locally. That's not much comfort.  If you are in a corporate setting, ask locally about proxy servers or other restrictions that might prevent this from working: `git clone -q https://github.com/MISP/PyMISP.git`

**Comment by adulau** [comment]
@chandan8893 As mentioned in the output, check the logs in `/tmp/pip-wheel-uvfcvufd/pymisp_f34e600d9f79400cadd5fd210d9ea1f9` I'll close the issue as it seems to be a local issue. Feel free to reopen if you have additional details.
