### ISSUE TITLE
Cortex module system…No modules found

### ISSUE THREAD

**Issue by khalidrehan** [MISP/misp-modules#471]
Hello,
I enabled Plugin.Cortex_services, and I was using Cortex ver. 3.0.1-1 on port 9001, and it gave "OK"
Then I migrated to Cortex 3.1.0-1 successfully, but it is giving "No modules found".
![image](https://user-images.githubusercontent.com/37035465/107972163-7e68c280-6fc4-11eb-978a-e4ccb61b3754.png)

Cortex is running fine, as well as MISP Modules service.

Where should I look for the problem?

Regards,
Khalid.

**Comment by adulau** [comment]
Cortex is not related to misp-modules. It's part of the TheHive project.
