### ISSUE TITLE
pip install of misp-modules fails on pandas requirements

### ISSUE THREAD

**Issue by adammchugh** [MISP/misp-modules#472]
From the installation instructions at https://github.com/MISP/misp-modules

`sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS`

fails during the requirements install with the following report.

```
ERROR: Could not find a version that satisfies the requirement pandas==1.2.1
ERROR: No matching distribution found for pandas==1.2.1
```

Incidentally, when updating REQUIREMENTS to instead require pandas==1.1.5 the installation will complete successfully.

**Comment by adammchugh** [comment]
Pull request https://github.com/MISP/misp-modules/pull/473 has been created to address this version change.

**Comment by adulau** [comment]
It should be fixed in the recent version of misp-modules. Feel free to reopen if this is not case.
