### ISSUE TITLE
Can we have a new tag, please? ;-)

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-modules#478]
https://github.com/MISP/misp-modules/issues/419#issuecomment-726806185
#456

**Comment by chrisinmtown** [comment]
I definitely get the sense that the CIRCL team does not have a lot of time for misp-modules.

**Comment by adulau** [comment]
Done. We did many changes and now there is a nice Changelog for new release, we split the CI integration (as we hit some limitation with current CI) and do an official release in GitHub. So tracking release of misp-modules, it will now be easier.
