### ISSUE TITLE
Update Wiki to point to correct File

### ISSUE THREAD

**Issue by bradchiappetta** [MISP/misp-modules#479]
Hello, so this may apply to a broader audience, but I noticed that the link in the Wiki (https://misp.github.io/misp-modules/expansion/#greynoise) for the GreyNoise expansion Hover points to:

'https://github.com/MISP/misp-modules/tree/master/misp_modules/modules/expansion/greynoise.py`

However, the latest version is actually

`https://github.com/MISP/misp-modules/blob/main/misp_modules/modules/expansion/greynoise.py`

Is it possible to get this fixed so folks are directed to the correct file?

Thanks!

**Comment by adulau** [comment]
Thanks for the notification. The documentation website has been updated.
