### ISSUE TITLE
uwhois module not installed.

### ISSUE THREAD

**Issue by giray** [MISP/misp-modules#48]
I'm getting an error

`uwhois module not installed.`

I've installed uwhoisd, but I cannot find a uwhois module ...

```
pip3 list | grep -i whois
cymruwhois (1.0)
uwhoisd (0.0.7)
whois (0.7)
```

**Comment by Rafiot** [comment]
What is the output of: 
```
pip install -U git+https://github.com/Rafiot/uwhoisd.git@testing#egg=uwhois&subdirectory=client
```

We had a problem is you use an old version of pip, so maybe you want to try the following before reinstalling uwhoisd client:
```
pip install -U pip
```

**Comment by giray** [comment]
So I removed the OS installed pip, and have 

`pip 8.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)`

however, I get the following error now when I query uwhoisd 


```
2016-09-07 10:28:07,115	INFO:uwhoisd	Querying whois.verisign-grs.com about google.com
2016-09-07 10:28:07,116	ERROR:uwhoisd	Unknown exception when querying 'domain  google.com'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/uwhoisd-0.0.7-py3.4.egg/uwhoisd/net.py", line 65, in whois
    self.sock.sendall('{0}\r\n'.format(query).encode())
AttributeError: 'WhoisClient' object has no attribute 'sock'
2016-09-07 10:28:07,116	ERROR:uwhoisd	Empty response for google.com

```

any ideas?

**Comment by Rafiot** [comment]
(for the records, uwhoisd is a bit messy right now, because I did many changes and I'm currently working on getting everything cleanly merged upstream)

Did you install and run `uwhosd` from  https://github.com/Rafiot/uwhoisd.git in the branch testing?

**Comment by giray** [comment]
Hi, 

  I got it from https://github.com/Rafiot/uwhoisd.git and it seems to be the testing branch indeed.

gd

**Comment by Rafiot** [comment]
... yeah, that makes sense, this branch if broken, I didn't try again after the last changes, sorry for that.

I'll try to fix it later today, but I'm not sure I'll have time...

**Comment by deloittem** [comment]
Hi,

Any news related to this ? I receive the same error when trying to install misp-module:

    sudo pip3 install -I -r REQUIREMENTS
    (git+https://github.com/Rafiot/uwhoisd.git@testing#egg=uwhois&subdirectory=client)

and then:

    misp-modules - INFO - MISP modules dns imported
    uwhois module not installed.

**Comment by 8ear** [comment]
Any news to it?

**Comment by Rafiot** [comment]
Not really, I need to look at it.

**Comment by jarandas** [comment]
Thank you logan-micklewright for the information. I will apply the changes you tell me.
Regards!!

**Comment by Rafiot** [comment]
The module now works and if configures, tries to connect to a uwhois instance (https://github.com/Lookyloo/uwhoisd)
