### ISSUE TITLE
misp-modules build failing at travis-ci since Summer 2020 

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#486]
Build of the misp-modules project at the travis-ci site fails. Apparently the most recent successful build was 9 months ago, the page doesn't show the exact date:

https://travis-ci.org/github/MISP/misp-modules/builds/703582728

It's really difficult to convince people in my company to deploy misp-modules with this evidence against it.  Please advise if you might fix the failing build soon, if I'm mis-interpreting the evidence here, etc.  Thanks.

**Comment by adulau** [comment]
We accept pull-request.

**Comment by chrisinmtown** [comment]
I would like to contribute via PRs but I work in an environment that requires legal review for all pull requests. So it's slow going for me.

Anyhow, since you mention that you accept PRs, I hope you will act on the 4 pull requests that are open today here in misp-modules.  Some have been open for months with no comment.

**Comment by adulau** [comment]
Accepting is not merging ;-)
