### ISSUE TITLE
REQUIREMENTS -i https://pypi.org/simple blocks use of pip conf index_url

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#505]
Please consider dropping this line from the misp-modules/REQUIREMENTS file:

https://github.com/MISP/misp-modules/blob/cb12d8a055bce4757df71fe081341836ac4329a3/REQUIREMENTS#L8

As far as I can tell, this -i argument overrides any index-url value set in pip.conf, which I am using to point pip at a PyPI mirror to avoid proxy issues. Also, pypi.org/simple is the default value for this argument, so this line is redundant anyhow.

This is the pip.conf file I'm using; some names have been changed to protect the innocent ;) 
```
[global]
index-url = https://pypi.it.mycompany.com
trusted-host = pypi.it.mycompany.com
```
Here's my proposed fix, thanks for considering it
```
% git diff REQUIREMENTS
diff --git a/REQUIREMENTS b/REQUIREMENTS
index 0fcfcb2..120d7c1 100644
--- a/REQUIREMENTS
+++ b/REQUIREMENTS
@@ -5,7 +5,6 @@
 #    pipenv lock --requirements
 #
 
--i https://pypi.org/simple
 -e .
 -e git+https://github.com/D4-project/BGP-Ranking.git/@fd9c0e03af9b61d4bf0b67ac73c7208a55178a54#egg=pybgpranking&subdirectory=client
 -e git+https://github.com/D4-project/IPASN-History.git/@fc5e48608afc113e101ca6421bf693b7b9753f9e#egg=pyipasnhistory&subdirectory=client
```

**Comment by adulau** [comment]
Thank you. It's indeed a good point, it's fixed. We might need to improve Pipfile generation into the requirements to avoid setting up the index.
