### ISSUE TITLE
Query: MISP software hashing and encryption

### ISSUE THREAD

**Issue by Sreejith2k** [MISP/misp-modules#509]
This is a query than issue.. I would like to know what type of hashing and encryption techniques are used in the MISP platform.

**Comment by mokaddem** [comment]
Hey,
Not sure what you are looking for exactly but MISP is storing user's password seeded and hashed in the DB and all synchronization are done using HTTPS. Additionally, users can configure plugins to handle authentication. And they can also use Certificate to validate users and remote MISP instances.
I hope that helps.
