### ISSUE TITLE
Pleae remove . (dot) from REQUIREMENTS file

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#510]
I see the first non-comment line in the REQUIREMENTS file is "." which seems really unusual. AFAIK the requirements file is supposed to list all the third-party Python packages that are required.  Would you please drop "."? I do not think you even need to adjust the current installation instructions because you already have this line in those instructions:
```
sudo -u www-data /var/www/MISP/venv/bin/pip install .
```

**Comment by ostefano** [comment]
I would suggest using `misp-modules` as published on PyPI, or migrate to `misp-docker`.
