### ISSUE TITLE
Custom misp-module runs into "1 object could not be saved. Reason for the failure: {"meta-category":["Meta-category cannot be empty."]}"

### ISSUE THREAD

**Issue by Stefan249** [MISP/misp-modules#521]
Hi everyone,

we are trying to develop a custom misp-module showing a link to another application. Therefore we created a misp-module including the following code to set a link:
        my_object = MISPObject('new-object')
        my_object.add_attribute('link', type='link', value='https://thisisatest.com')
        self.my_object.add_object(**my_object)

The new-object looks like this:
{
  "attributes": {
    "link": {
      "categories": [
        "External analysis"
      ],
      "description": "Permalink Reference",
      "disable_correlation": true,
      "misp-attribute": "link",
      "ui-priority": 0
    }
  },
  "description": "new-object",
  "meta-category": "misc",
  "name": "new-object",
  "requiredOneOf": [
    "link"
  ],
  "uuid": "2d357471-ab43-4e84-b889-38adea34a916",
  "version": 1
}

After updating the object and updating the misp-modules everything seems to work fine: hovering shows the links and "Enrich event" creates the object for each attribute in the event. But if we click onto the single attribute "Add Enrichment" button (picture),
![Screenshot 2021-08-27 at 17 03 43](https://user-images.githubusercontent.com/72857835/131148445-623f118d-871d-4550-9b2c-342bcdaef19e.png)
the following error is received (Job section):
"1 object could not be saved. Reason for the failure: {"meta-category":["Meta-category cannot be empty."]}""
As the meta-category is set, the "Enrich event" works and creates the object it might be a bug. When we just change the object to one that has already existed it works again. If we copy that object, change the name and UUID the error appears again. Has anyone the same issue? 

Thanks 
Stefan

**Comment by adulau** [comment]
Don't hesitate to reopen the issue if you think it's not fixed in the meantime.
