### ISSUE TITLE
 pip3 install -I -r REQUIREMENTS fails: trustar-0.3.35 dependency

### ISSUE THREAD

**Issue by rene-r-martinez** [MISP/misp-modules#523]
Getting an error installing. Log details below 

Downloading trustar-0.3.35.tar.gz (51 kB)
    ERROR: Command errored out with exit status 1:
        command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r6or4o9u/trustar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r6or4o9u/trustar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r6or4o9u/trustar/pip-egg-info
                cwd: /tmp/pip-install-r6or4o9u/trustar/
     Complete output (3 lines):
      /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
       warnings.warn(
     error in trustar setup command: use_2to3 is invalid.
     ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by github-germ** [comment]
You need to downgrade your version of `setuptools`.

The trustar install uses a the `use_2to3` feature in `setuptools`. That feature was discontinued in the new v58.0.0 release of setuptools on 9/4/2021.

See https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0 and https://github.com/pypa/setuptools/issues/2086
v58.0.0
04 Sep 2021
Breaking Changes
  . #2086: Removed support for 2to3 during builds. Projects should
    port to a unified codebase or pin to an older version of
    Setuptools using PEP 518 build-requires.

**Comment by rene-r-martinez** [comment]
Thanks, enforcing version 57.5.0 fixed the issue.
