### ISSUE TITLE
misp modules installation issue

### ISSUE THREAD

**Issue by Klaas-Vaak** [MISP/misp-modules#524]
OS: Ubuntu 18.04 / CentOS 7
MISP: v2.4.148

When installing the misp-modules for both Ubuntu 18.04 and CentOS 7, a error occurs for pandas 1.3.2. 
On both distro's I'm unable to get the right pandas version.

Error
`Downloading pandas_ods_reader-0.1.2-py3-none-any.whl (7.6 kB)
ERROR: Could not find a version that satisfies the requirement pandas==1.3.2 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)                                                
ERROR: No matching distribution found for pandas==1.3.2`

I retried it on Ubuntu 20.04 which didn't threw a error like this and seems to run fine.

Since our major Linux deployment is running on the CentOS 7 distro I would rather go for this then Ubuntu 20.04. 
Any ideas or solutions how to solve this? Thanks in advance!

**Comment by cybgit** [comment]
Same here - Ubuntu 18.04

**Comment by ostefano** [comment]
I would suggest using `misp-modules` as published on PyPI, or migrate to `misp-docker`.
