### ISSUE TITLE
Conflicting install documentation

### ISSUE THREAD

**Issue by korrosivesec** [MISP/misp-modules#527]
There are two different sets of instructions for installing misp-modules in a virtualenv:

- [README.md](https://github.com/MISP/misp-modules/blob/main/README.md#how-to-install-and-start-misp-modules-in-a-python-virtualenv-recommended)
- [https://misp.github.io/misp-modules/install/](https://github.com/MISP/misp-modules/blob/main/documentation/mkdocs/install.md#how-to-install-and-start-misp-modules-in-a-python-virtualenv)

The README has been updated most recently, but not sure which set of instructions is the preferred method.

**Comment by zero060699** [comment]
I can not install REQUIREMENTS, help me

**Comment by ostefano** [comment]
This has been fixed.
