### ISSUE TITLE
Error installing importlib-metadata==4.10.1 under RHEL8

### ISSUE THREAD

**Issue by clopmz** [MISP/misp-modules#553]
Hi all,

Doing a RHEL8.5 (fully patched) fresh install, command "pip install -U -I -r REQUIREMENTS" returns the following error:

Processing /opt/misp-modules
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Ignoring filelock: markers 'python_version >= "3.7"' don't match your environment
Ignoring frozenlist: markers 'python_version >= "3.7"' don't match your environment
Collecting pybgpranking
  Cloning https://github.com/D4-project/BGP-Ranking.git/ (to revision 68de39f6c5196f796055c1ac34504054d688aa59) to /tmp/pip-install-13rgnlq7/pybgpranking_2ab5ed989c9a4695969646d579b79bc0
  Running command git clone --filter=blob:none -q https://github.com/D4-project/BGP-Ranking.git/ /tmp/pip-install-13rgnlq7/pybgpranking_2ab5ed989c9a4695969646d579b79bc0
  Running command git rev-parse -q --verify 'sha^68de39f6c5196f796055c1ac34504054d688aa59'
  Running command git fetch -q https://github.com/D4-project/BGP-Ranking.git/ 68de39f6c5196f796055c1ac34504054d688aa59
  Running command git checkout -q 68de39f6c5196f796055c1ac34504054d688aa59
  Resolved https://github.com/D4-project/BGP-Ranking.git/ to commit 68de39f6c5196f796055c1ac34504054d688aa59
  Preparing metadata (setup.py) ... done
Collecting pyipasnhistory
  Cloning https://github.com/D4-project/IPASN-History.git/ (to revision a2853c39265cecdd0c0d16850bd34621c0551b87) to /tmp/pip-install-13rgnlq7/pyipasnhistory_2cc003a74f0e484c8d016f7a01b867f2
  Running command git clone --filter=blob:none -q https://github.com/D4-project/IPASN-History.git/ /tmp/pip-install-13rgnlq7/pyipasnhistory_2cc003a74f0e484c8d016f7a01b867f2
  Running command git rev-parse -q --verify 'sha^a2853c39265cecdd0c0d16850bd34621c0551b87'
  Running command git fetch -q https://github.com/D4-project/IPASN-History.git/ a2853c39265cecdd0c0d16850bd34621c0551b87
  Running command git checkout -q a2853c39265cecdd0c0d16850bd34621c0551b87
  Resolved https://github.com/D4-project/IPASN-History.git/ to commit a2853c39265cecdd0c0d16850bd34621c0551b87
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Collecting pyintel471
  Cloning https://github.com/MISP/PyIntel471.git (to revision 917272fafa8e12102329faca52173e90c5256968) to /tmp/pip-install-13rgnlq7/pyintel471_f42b8c82b2774883af1abcaf33bf2993
  Running command git clone --filter=blob:none -q https://github.com/MISP/PyIntel471.git /tmp/pip-install-13rgnlq7/pyintel471_f42b8c82b2774883af1abcaf33bf2993
  Running command git rev-parse -q --verify 'sha^917272fafa8e12102329faca52173e90c5256968'
  Running command git fetch -q https://github.com/MISP/PyIntel471.git 917272fafa8e12102329faca52173e90c5256968
  Resolved https://github.com/MISP/PyIntel471.git to commit 917272fafa8e12102329faca52173e90c5256968
  Preparing metadata (setup.py) ... done
Collecting trustar
  Cloning https://github.com/SteveClement/trustar-python.git (to revision 6954eae38e0c77eaeef26084b6c5fd033925c1c7) to /tmp/pip-install-13rgnlq7/trustar_30e31caf5968409abdd63019787c6e64
  Running command git clone --filter=blob:none -q https://github.com/SteveClement/trustar-python.git /tmp/pip-install-13rgnlq7/trustar_30e31caf5968409abdd63019787c6e64
  Running command git rev-parse -q --verify 'sha^6954eae38e0c77eaeef26084b6c5fd033925c1c7'
  Running command git fetch -q https://github.com/SteveClement/trustar-python.git 6954eae38e0c77eaeef26084b6c5fd033925c1c7
  Resolved https://github.com/SteveClement/trustar-python.git to commit 6954eae38e0c77eaeef26084b6c5fd033925c1c7
  Preparing metadata (setup.py) ... done
Collecting odtreader
  Cloning https://github.com/cartertemm/ODTReader.git/ (to revision 49d6938693f6faa3ff09998f86dba551ae3a996b) to /tmp/pip-install-13rgnlq7/odtreader_32f8feb70da64a84a8d71628da2a69e2
  Running command git clone --filter=blob:none -q https://github.com/cartertemm/ODTReader.git/ /tmp/pip-install-13rgnlq7/odtreader_32f8feb70da64a84a8d71628da2a69e2
  Running command git rev-parse -q --verify 'sha^49d6938693f6faa3ff09998f86dba551ae3a996b'
  Running command git fetch -q https://github.com/cartertemm/ODTReader.git/ 49d6938693f6faa3ff09998f86dba551ae3a996b
  Resolved https://github.com/cartertemm/ODTReader.git/ to commit 49d6938693f6faa3ff09998f86dba551ae3a996b
  Preparing metadata (setup.py) ... done
Collecting pydnstrails
  Cloning https://github.com/sebdraven/pydnstrails (to revision 48c1f740025c51289f43a24863d1845ff12fd21a) to /tmp/pip-install-13rgnlq7/pydnstrails_0c79cd3ce3624bfc810f947ff33a6cd8
  Running command git clone --filter=blob:none -q https://github.com/sebdraven/pydnstrails /tmp/pip-install-13rgnlq7/pydnstrails_0c79cd3ce3624bfc810f947ff33a6cd8
  Running command git rev-parse -q --verify 'sha^48c1f740025c51289f43a24863d1845ff12fd21a'
  Running command git fetch -q https://github.com/sebdraven/pydnstrails 48c1f740025c51289f43a24863d1845ff12fd21a
  Resolved https://github.com/sebdraven/pydnstrails to commit 48c1f740025c51289f43a24863d1845ff12fd21a
  Preparing metadata (setup.py) ... done
Collecting pyonyphe
  Cloning https://github.com/sebdraven/pyonyphe (to revision aed008ee5a27e3a5e4afbb3e5cbfc47170108452) to /tmp/pip-install-13rgnlq7/pyonyphe_2478bb890a3a43b689e8585f8fe71e09
  Running command git clone --filter=blob:none -q https://github.com/sebdraven/pyonyphe /tmp/pip-install-13rgnlq7/pyonyphe_2478bb890a3a43b689e8585f8fe71e09
  Running command git rev-parse -q --verify 'sha^aed008ee5a27e3a5e4afbb3e5cbfc47170108452'
  Running command git fetch -q https://github.com/sebdraven/pyonyphe aed008ee5a27e3a5e4afbb3e5cbfc47170108452
  Resolved https://github.com/sebdraven/pyonyphe to commit aed008ee5a27e3a5e4afbb3e5cbfc47170108452
  Preparing metadata (setup.py) ... done
Ignoring keyring: markers 'python_version >= "3.7"' don't match your environment
Ignoring multidict: markers 'python_version >= "3.7"' don't match your environment
Ignoring progressbar2: markers 'python_version >= "3.7"' don't match your environment
Ignoring pyrsistent: markers 'python_version >= "3.7"' don't match your environment
Ignoring python-utils: markers 'python_version >= "3.7"' don't match your environment
Ignoring rdflib: markers 'python_version >= "3.7"' don't match your environment
Ignoring setuptools: markers 'python_version >= "3.7"' don't match your environment
Ignoring zipp: markers 'python_version >= "3.7"' don't match your environment
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Collecting apiosintds==1.8.3
  Downloading apiosintDS-1.8.3-py3-none-any.whl (13 kB)
Collecting appdirs==1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting argparse==1.4.0
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting assemblyline-client==4.2.2
  Downloading assemblyline_client-4.2.2-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 1.0 MB/s
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting asynctest==0.13.0
  Using cached asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting backoff==1.11.1
  Using cached backoff-1.11.1-py2.py3-none-any.whl (13 kB)
Collecting backports.zoneinfo==0.2.1
  Downloading backports.zoneinfo-0.2.1-cp36-cp36m-manylinux1_x86_64.whl (70 kB)
     |████████████████████████████████| 70 kB 7.8 MB/s
Collecting backscatter==0.2.4
  Downloading backscatter-0.2.4-py3-none-any.whl (11 kB)
Collecting beautifulsoup4==4.10.0
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 8.2 MB/s
Collecting bidict==0.21.4
  Downloading bidict-0.21.4-py3-none-any.whl (36 kB)
Collecting blockchain==1.4.4
  Downloading blockchain-1.4.4.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... done
Collecting censys==2.1.2
  Using cached censys-2.1.2-py3-none-any.whl (53 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (405 kB)
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 19.3 MB/s
Collecting charset-normalizer==2.0.11
  Using cached charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
Collecting clamd==1.0.2
  Downloading clamd-1.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting click-plugins==1.1.1
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting click==8.0.3
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 6.7 MB/s
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting colorclass==2.2.2
  Downloading colorclass-2.2.2-py2.py3-none-any.whl (18 kB)
Collecting commonmark==0.9.1
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting compressed-rtf==1.0.6
  Downloading compressed_rtf-1.0.6.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Collecting configparser==5.2.0
  Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting crowdstrike-falconpy==1.0.0
  Downloading crowdstrike_falconpy-1.0.0-py3-none-any.whl (357 kB)
     |████████████████████████████████| 357 kB 19.2 MB/s
Collecting cryptography==36.0.1
  Using cached cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting decorator==5.1.1
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting deprecated==1.2.13
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting dnsdb2==1.1.3
  Using cached dnsdb2-1.1.3-py3-none-any.whl
Collecting dnspython==2.2.0
  Downloading dnspython-2.2.0-py3-none-any.whl (266 kB)
     |████████████████████████████████| 266 kB 30.7 MB/s
Collecting domaintools-api==0.6.1
  Downloading domaintools_api-0.6.1-py2.py3-none-any.whl (18 kB)
Collecting easygui==0.98.2
  Downloading easygui-0.98.2-py2.py3-none-any.whl (92 kB)
     |████████████████████████████████| 92 kB 13.6 MB/s
Collecting ebcdic==1.1.1
  Downloading ebcdic-1.1.1-py2.py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 18.0 MB/s
Collecting enum-compat==0.0.3
  Downloading enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Collecting extract-msg==0.28.7
  Downloading extract_msg-0.28.7-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 11.0 MB/s
Collecting ezodf==0.3.2
  Downloading ezodf-0.3.2.tar.gz (125 kB)
     |████████████████████████████████| 125 kB 19.3 MB/s
  Preparing metadata (setup.py) ... done
Collecting future==0.18.2
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 21.3 MB/s
  Preparing metadata (setup.py) ... done
Collecting geoip2==4.5.0
  Downloading geoip2-4.5.0-py2.py3-none-any.whl (26 kB)
Collecting httplib2==0.20.4
  Downloading httplib2-0.20.4-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 6.6 MB/s
Collecting idna-ssl==1.1.0
  Using cached idna_ssl-1.1.0-py3-none-any.whl
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imapclient==2.1.0
  Downloading IMAPClient-2.1.0-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 3.2 MB/s
ERROR: Could not find a version that satisfies the requirement importlib-metadata==4.10.1 (from versions: 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.7.0, 4.7.1, 4.8.0, 4.8.1, 4.8.2, 4.8.3)
ERROR: No matching distribution found for importlib-metadata==4.10.1

How can I fix this?

**Comment by cedricbonhomme** [comment]
Hi,

Are you using Python 3.6 ? If yes, be careful: it has [reached end-of-life](https://www.python.org/downloads/release/python-360/). 

And in your case, the version 4.10.1 of importlib-metadata is only compatible with Python >=3.7. Same for misp-modules itself.

As you can see there are a lot of messages like ```'python_version >= "3.7"' don't match your environment```

**Comment by JakubOnderka** [comment]
Hello, you can install Python 3.9 from app stream. See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python

**Comment by clopmz** [comment]
Thanks .... I am installing a new MISP server due to a problems related to php-redis and I will use python39.
