### ISSUE TITLE
clamav module missing from module list and does not install

### ISSUE THREAD

**Issue by marcrusa** [MISP/misp-modules#561]
The clamav module is not listed under Expansion modules and does not install.  There are no options in the Plugin settings for it and it not running even though the modules installed without any errors.

**Comment by marcrusa** [comment]
If I start the modules in diagnostic mode then it works.

**Comment by adulau** [comment]
Indeed good catch. It should be fixed with https://github.com/MISP/misp-modules/commit/c384c3a2a576cd78a80bb5b86ba8faf8722cd977 

Thank you for the report.
