### ISSUE TITLE
Error in `/opt/misp/MISP/venv/bin/python': free(): invalid pointer

### ISSUE THREAD

**Issue by eowyn263** [MISP/misp-modules#568]
Hello,

I'm getting error message when trying to start misp-modules.service:
`Error in `/opt/misp/MISP/venv/bin/python': free(): invalid pointer`

I was following [this manual](https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules-on-rhel-based-distributions-)

I'm using rhel7 and MISP version v2.4.158.

Would be grateful for any help!

Thanks!

**Comment by adulau** [comment]
Can you tell me which version of Python you are using?

**Comment by eowyn263** [comment]
Hi, it's 3.8

**Comment by eowyn263** [comment]
Hey @adulau, there was the same issue as in https://github.com/MISP/misp-modules/issues/48

When I removed  `qrcode`, `ocr_enrich` and `pdf_enrich` from `/var/www/MISP/venv/lib/python3.8/site-packages/misp_modules/modules/expansion` the service was able to start properly.  `qrcode` and `ocr_enrich` were complaining about cv2.

**Comment by adulau** [comment]
Thank you very much for the feedback. I'll have a look at cv2 issues.
