### ISSUE TITLE
I got this error when run update_misp_module.sh script

### ISSUE THREAD

**Issue by Aledangelo** [MISP/misp-modules#588]
I run this script on linux, this is the script permission:
-rwxr-xr-x 1 misp staff 1168 14 set 18.34 update_misp_modules.sh

Error:

+ '[' -d /var/www/MISP ']'
+ '[' -d /usr/local/src/misp-modules ']'
+ echo 'MISP is installed on the same machine, following the recommanded install script. Using MISP virtualenv.'
MISP is installed on the same machine, following the recommanded install script. Using MISP virtualenv.
+ PATH_TO_MISP=/var/www/MISP
+ PATH_TO_MISP_MODULES=/usr/local/src/misp-modules
+ pushd /usr/local/src/misp-modules
/usr/local/src/misp-modules /home/ale
++ stat -c %U .
+ USER=misp
+ sudo -H -u misp git pull
Già aggiornato.
+ sudo -H -u misp /var/www/MISP/venv/bin/pip install -U -r REQUIREMENTS
Ignoring asynctest: markers 'python_version < "3.8"' don't match your environment
Ignoring backports.zoneinfo: markers 'python_version < "3.9"' don't match your environment
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment
Processing /usr/local/src/misp-modules
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: [Errno 13] Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by MU-03** [comment]
I am also facing this exact error. Can you kindly guide me if you have solved this. Thank you.

**Comment by adulau** [comment]
@MU-03 If you want to update your module `git pull origin` and `pip install .`  works out-of-the-box

**Comment by MU-03** [comment]
> > I am also facing this exact error. Can you kindly guide me if you have solved this. Thank you.
> 
> Sorry man, instead of trying to fix it, I just changed software

Okay, no problem

**Comment by MU-03** [comment]
> @MU-03 If you want to update your module `git pull origin` and `pip install .` works out-of-the-box
Thanks

**Comment by MU-03** [comment]
> @MU-03 If you want to update your module `git pull origin` and `pip install .` works out-of-the-box

I am also facing an issue with enrichment of event, when I click on ''Enrich Event" its not giving any options even tho I enabled enrichment in the plug-ins.
Kindly help if you know the solution.

**Comment by ostefano** [comment]
We are now publishing a package on pypi. Update using that, or migrate to misp-docker.
