### ISSUE TITLE
Mismatch version for psutil

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-modules#593]
On a clean setup there was a version mismatch error for psutil

```
/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -d
Traceback (most recent call last):
  File "/var/www/MISP/venv/bin/misp-modules", line 5, in <module>
    from misp_modules import main
  File "/var/www/MISP/venv/lib/python3.8/site-packages/misp_modules/__init__.py", line 32, in <module>
    import psutil
  File "/var/www/MISP/venv/lib/python3.8/site-packages/psutil/__init__.py", line 241, in <module>
    raise ImportError(msg)
ImportError: version conflict: '/var/www/MISP/venv/lib/python3.8/site-packages/psutil/_psutil_linux.cpython-38-x86_64-linux-gnu.so' C extension module was built for another version of psutil (5.9.2 instead of 5.9.4); you may try to 'pip uninstall psutil', manually remove /var/www/MISP/venv/lib/python3.8/site-packages/psutil/_psutil_linux.cpython-38-x86_64-linux-gnu.so or clean the virtual env somehow, then reinstall
```

Uninstalling psutil and then re-installing it solved the problem.

This happened on a "new" Ubuntu 20.04.

**Comment by knightian** [comment]
Same, Ubuntu 22.04 after building and trying to run the modules.

will try  the uninstall reinstall of psutils

**Comment by RonV666** [comment]
Indeed I tried both 22.04 and 20.04 and could never get the modules to run.

I ended up on 20.04 using the  

 sudo $SUDO_WWW /var/www/MISP/venv/bin/pip uninstall psutil
 sudo systemctl start misp-modules

workaround and this does indeed work. I didn't re-install anything however, is that required?

**Comment by knightian** [comment]
> I didn't re-install anything however, is that required?

I had 2 conflicting psutil so probably like me you have removed one of the versions. If it throws an error about a version mismatch I can’t see why it would not throw an error if it completely doesn’t exist 🤣 So I’d say you’re all good now.

**Comment by thomaspatzke** [comment]
There are two conflicting dependencies defined in [REQUIREMENTS](https://github.com/MISP/misp-modules/blob/b8de83e9f5a93890fec71f965d052a9e260df0e0/REQUIREMENTS#L98) and [setup.py](https://github.com/MISP/misp-modules/blob/3b58915c41fdea25b2f012d18c4231fcada3e350/setup.py#L27). I think it would be cleaner to use only one source for dependencies.

**Comment by fukusuket** [comment]
I installed the latest version of [misp-module(8579cbb)](https://github.com/MISP/misp-modules/commit/8579cbb260820aaa738ee13d18d11e7d0ed0e387) (by `INSTALL.sh -c -M`) on clean Ubuntu 20.04  and confirmed that it works. [This commit](https://github.com/MISP/misp-modules/commit/8579cbb260820aaa738ee13d18d11e7d0ed0e387) seems to have fixed the problem. Thank you for the fix :)

**Comment by adulau** [comment]
Thanks for the feedback!
