### ISSUE TITLE
Cytomic_orion.py - unable to connect to token_url

### ISSUE THREAD

**Issue by PiLoT650** [MISP/misp-modules#612]
Hello, i'm trying to get a testsystem working with Cytomic Orion (Watchguard) and misp.
Followed as far as i could this tutorial: https://www.vanimpe.eu/2020/03/10/integrating-misp-and-cytomic-orion/
While running cytomic_orion.py i get this error:

` from pymisp import ExpandedPyMISP
Unable to connect to token_url
`

These are the values i've set in the enrichment settings
![cytomic_orion_settings](https://github.com/MISP/misp-modules/assets/50521598/0e589b3e-61df-48eb-97c6-224b40082e91)

Any help/tip appreciated.
Thank you

**Comment by cudeso** [comment]
Hello,

Are you able to connect to auth.pandasecurity.com from the system where MISP modules is installed? 
- Check if you need to use a proxy and if network resolving works
- Do a curl POST request to the token_url URL and check if you can access it

kr,

koen

**Comment by PiLoT650** [comment]
Hello @cudeso thanks for your input - in meantime i had a look for the sourcecode and postman/orion docus.

The right URLs for Watchguard Cytomic Orion / MISP are:
**ORION_API_URL** = https://api.orion.cytomic.ai/api/v1/applications/
**ORION_TOKEN_URL** = https://auth.pandasecurity.com/oauth/token
with these two i get a token and also the cytomic enrichment module works as it should.

Second thing im working on now - ist to push / upload / delete via cytomic_orion.py
which won't work for now. i do not get an error - but also the script wont push / pull any iocs/events.

Seems like i am missing some option/tag for the script to work on it. I've added the taxonomie / tags and created two test events with the cytomic uppload tag.

rom pymisp import ExpandedPyMISP
Received access token
cytomic-orion:action="upload" _<-- added these to check if upload tag is set_
cytomic-orion:action="upload" _<-- added these to check if upload tag is set_
Searching for attributes of type ip-dst
Searching for attributes of type ip-src
Searching for attributes of type url
Searching for attributes of type md5
Searching for attributes of type domain
Searching for attributes of type hostname
Searching for attributes of type domain|ip
Searching for attributes of type hostname|port

any ideas?
thank you - kr PiLoT

**Comment by PiLoT650** [comment]
Hello, got it - IDS seems to be mandatory for upload - at least was the only thing i changed and now it's working.
![image](https://github.com/MISP/misp-modules/assets/50521598/f30d090f-d29b-4540-acbc-5d8b3550eb2a)


Thank you
kr PiLoT
