### ISSUE TITLE
Version discrepancies between misp-modules and MISP

### ISSUE THREAD

**Issue by skalvaro** [MISP/misp-modules#631]
Several requirements in misp-modules install different version then what is installed with misp itself.
Example is pymisp which in the requirements of misp-modules is fixed on 2.4.167 while an update of misp itself will install the latest version.

Recently we had issues with yara-python for which the advise was to update it to the latest version but again the requirements of misp-modules fixes this package to 3.8.1.

misp-modules also has an update script, update_misp_modules.sh, which when used will install the versions mentioned in the requirements.

Another example is apiosintds with its dependency on pytz==2019.3 while misp-stix needs 2022.2.1.

The question is how to keep misp and misp-modules up-to-date with all of the dependencies and differences in them.

OS: Ubuntu 22.04.2 LTS

**Comment by elvidence** [comment]
I tested most of the modules the complained with the new pymisp, putz and so on. They all work fine. I then ended up going to 
/var/www/MISP/venv/lib/python3.10/site-packages/vysion-1.0.10.dist-info/METADATA  
/var/www/MISP/venv/lib/python3.10/site-packages/censys …./METADATA  etc etc  
and directly editing the METADATA  files similar to: 
Requires-Dist: requests (>=2.29.0,<2.33.0) 
Requires-Dist: urllib3 (>=2.2.2)
 Requires-Dist: pymisp (>=2.4.175,<2.5) 
 
 No more complains and everything is stable and working

**Comment by ostefano** [comment]
I would run MISP and MISP-modules on two separate virtual environments. Even better, migrate to `misp-docker`.
