### ISSUE TITLE
Errors with Requirements Check

### ISSUE THREAD

**Issue by lululemon-harry** [MISP/misp-modules#638]
Hello, when I am running the Requirements check for the modules I get this error using the latest MISP repo.

`ERROR: Could not find a version that satisfies the requirement lief==0.13.2 (from -r REQUIREMENTS (line 68)) (from versions: 0.8.0.post7, 0.8.1.post1, 0.8.2.post1, 0.8.3.post3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.12.0, 0.12.1, 0.12.2, 0.12.3)
ERROR: No matching distribution found for lief==0.13.2 (from -r REQUIREMENTS (line 68))`

I'm using Ubuntu 20. Anyone else get this when setting up a fresh MISP instance ?

**Comment by ostefano** [comment]
I would suggest using `misp-modules` as published on PyPI, or migrate to `misp-docker`.
