### ISSUE TITLE
Revised Requirements for MISP Modules

### ISSUE THREAD

**Issue by elvidence** [MISP/misp-modules#674]
Please review and revise the requirements for building MISP modules. Currently, it's exceedingly challenging to compile the modules because of several conflicting dependencies, including but not limited to 'lief', 'validators', and others. This situation creates a barrier to successful installation and operation. 

OS. Ubuntu 22.04
Python 3.10
PHP 7.4

**Comment by adulau** [comment]
We are evaluating to have multiple requirements files for each modules to facilitate the deployments of the misp modules. If you have some good ideas (usually you have good ones), let  us know.

**Comment by ostefano** [comment]
This is now solved thanks to poetry.
