### ISSUE TITLE
set first_seen and last_seen propertues on passive-dns object using time_first and time_last

### ISSUE THREAD

**Issue by righel** [MISP/misp-modules#692]
Improves the UX of the event timeline when using passive-dns enrichment
https://github.com/MISP/misp-modules/blob/7623b3c615501a9853cdaf3bfc26f16512993a8c/misp_modules/modules/expansion/circl_passivedns.py#L56C13-L56C24

**Comment by adulau** [comment]
Good catch. I'll update thx.
