### ISSUE TITLE
Email Import Module and Attachment Attribute Mapping Suggestion

### ISSUE THREAD

**Issue by cyber-guy** [MISP/misp-modules#90]
This is just a suggestion. When using the Email Import Module, attachments are mapped as attributes with Category : External analysis and Type: attachment

This looks due to the values choice in email.import.py
185 for attch_item in attachment_files:
**186 	attch_item["types"] = ['attachment']**
187 	results.append(attch_item)

Perhaps a better choice for mapping would be to use ['email-attachment'] which is within Payload delivery?

By using attachment, MISP thinks the attribute object is actually a saved file and will offer the ability to download it (which of course it isn't actually saved or downloadable)

**Comment by Rafiot** [comment]
email-attachment is only the file name of the attachment, not the full attachment.

The current implementation will fail, we need to use the data keyword, and I think the right type to use is malware-sample in that case. 
What do you think?

**Comment by Rafiot** [comment]
What do you think of that one?

**Comment by cyber-guy** [comment]
That could work. I was thinking the code was just trying to extract the name of the attachment itself and not the actual full attachment file so that's why i was suggesting email-attachment value. 

If it's the full attachment, malware-sample should work. I did try adding a test attribute with category Payload Delivery and type malware-sample and it would not let me save the attribute "Error: [InternalErrorException] Composite type, but value not explodable" but that could be another issue altogether

**Comment by Rafiot** [comment]
I didn't test the code at all, I'll work on that later today or tomorrow

**Comment by Rafiot** [comment]
Definitely need some more work: https://travis-ci.org/Rafiot/misp-modules/jobs/189849425

**Comment by Rafiot** [comment]
Fixed.
