### ISSUE TITLE
UTF encoding causing errors

### ISSUE THREAD

**Issue by seamustuohy** [MISP/misp-modules#93]
After a casual mention by @Rafiot that UTF encoding caused errors when importing emails in the e-mail import module I created some [unit-tests](https://github.com/seamustuohy/misp-modules/blob/0566049c630c0595b44984ace3fde4457ac6af60/tests/test.py#L318-L356) so I could figure out how to fix it. Yet, the unit-tests will not fail under UTF 8, 16, or 32 in  the body or the headers. So, I am adding this issue so @Rafiot can attach a failing e-mail and I can reproduce the aforementioned UTF issues.

**Comment by Rafiot** [comment]
I need to try that again, I may have fixed it there: https://github.com/MISP/misp-modules/commit/1051e2210b65be4c215c3ad17e46a624eb0081cb which was due to the removal of `mode='U'` in python3.6: https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open

**Comment by Rafiot** [comment]
Fixed
